// lib/services/puzzle_data.dart
// 500 video game puzzles: 150 Easy, 200 Medium, 150 Hard

import 'dart:math';
import '../models/puzzle_model.dart';

class PuzzleData {
  static const List<PuzzleModel> easyPuzzles = [
    PuzzleModel(id:'e001', answer:'MINECRAFT', category:'Sandbox', difficulty:Difficulty.easy),
    PuzzleModel(id:'e002', answer:'MARIO KART', category:'Racing', difficulty:Difficulty.easy),
    PuzzleModel(id:'e003', answer:'TETRIS', category:'Puzzle', difficulty:Difficulty.easy),
    PuzzleModel(id:'e004', answer:'PAC MAN', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e005', answer:'FORTNITE', category:'Battle Royale', difficulty:Difficulty.easy),
    PuzzleModel(id:'e006', answer:'POKEMON', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e007', answer:'SONIC', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e008', answer:'DOOM', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e009', answer:'ZELDA', category:'Adventure', difficulty:Difficulty.easy),
    PuzzleModel(id:'e010', answer:'FIFA', category:'Sports', difficulty:Difficulty.easy),
    PuzzleModel(id:'e011', answer:'AMONG US', category:'Social', difficulty:Difficulty.easy),
    PuzzleModel(id:'e012', answer:'ROBLOX', category:'Sandbox', difficulty:Difficulty.easy),
    PuzzleModel(id:'e013', answer:'MARIO', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e014', answer:'HALO', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e015', answer:'SIMS', category:'Simulation', difficulty:Difficulty.easy),
    PuzzleModel(id:'e016', answer:'PONG', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e017', answer:'SNAKE', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e018', answer:'ANGRY BIRDS', category:'Mobile', difficulty:Difficulty.easy),
    PuzzleModel(id:'e019', answer:'CANDY CRUSH', category:'Mobile', difficulty:Difficulty.easy),
    PuzzleModel(id:'e020', answer:'CLASH OF CLANS', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e021', answer:'OVERWATCH', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e022', answer:'WARCRAFT', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e023', answer:'DIABLO', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e024', answer:'STARCRAFT', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e025', answer:'HEARTHSTONE', category:'Card Game', difficulty:Difficulty.easy),
    PuzzleModel(id:'e026', answer:'PUBG', category:'Battle Royale', difficulty:Difficulty.easy),
    PuzzleModel(id:'e027', answer:'APEX LEGENDS', category:'Battle Royale', difficulty:Difficulty.easy),
    PuzzleModel(id:'e028', answer:'VALORANT', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e029', answer:'LEAGUE OF LEGENDS', category:'MOBA', difficulty:Difficulty.easy),
    PuzzleModel(id:'e030', answer:'DOTA', category:'MOBA', difficulty:Difficulty.easy),
    PuzzleModel(id:'e031', answer:'COUNTER STRIKE', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e032', answer:'CALL OF DUTY', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e033', answer:'GRAND THEFT AUTO', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e034', answer:'RED DEAD REDEMPTION', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e035', answer:'CYBERPUNK', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e036', answer:'WITCHER', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e037', answer:'SKYRIM', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e038', answer:'FALLOUT', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e039', answer:'RESIDENT EVIL', category:'Horror', difficulty:Difficulty.easy),
    PuzzleModel(id:'e040', answer:'SILENT HILL', category:'Horror', difficulty:Difficulty.easy),
    PuzzleModel(id:'e041', answer:'METAL GEAR', category:'Stealth', difficulty:Difficulty.easy),
    PuzzleModel(id:'e042', answer:'STREET FIGHTER', category:'Fighting', difficulty:Difficulty.easy),
    PuzzleModel(id:'e043', answer:'MORTAL KOMBAT', category:'Fighting', difficulty:Difficulty.easy),
    PuzzleModel(id:'e044', answer:'TEKKEN', category:'Fighting', difficulty:Difficulty.easy),
    PuzzleModel(id:'e045', answer:'FIFA', category:'Sports', difficulty:Difficulty.easy),
    PuzzleModel(id:'e046', answer:'NBA', category:'Sports', difficulty:Difficulty.easy),
    PuzzleModel(id:'e047', answer:'MADDEN', category:'Sports', difficulty:Difficulty.easy),
    PuzzleModel(id:'e048', answer:'ROCKET LEAGUE', category:'Sports', difficulty:Difficulty.easy),
    PuzzleModel(id:'e049', answer:'DIRT RALLY', category:'Racing', difficulty:Difficulty.easy),
    PuzzleModel(id:'e050', answer:'NEED FOR SPEED', category:'Racing', difficulty:Difficulty.easy),
    PuzzleModel(id:'e051', answer:'BURNOUT', category:'Racing', difficulty:Difficulty.easy),
    PuzzleModel(id:'e052', answer:'GRAN TURISMO', category:'Racing', difficulty:Difficulty.easy),
    PuzzleModel(id:'e053', answer:'FORZA', category:'Racing', difficulty:Difficulty.easy),
    PuzzleModel(id:'e054', answer:'LUIGI', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e055', answer:'YOSHI', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e056', answer:'KIRBY', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e057', answer:'DONKEY KONG', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e058', answer:'PIKACHU', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e059', answer:'SPLATOON', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e060', answer:'ANIMAL CROSSING', category:'Simulation', difficulty:Difficulty.easy),
    PuzzleModel(id:'e061', answer:'STARDEW VALLEY', category:'Simulation', difficulty:Difficulty.easy),
    PuzzleModel(id:'e062', answer:'TERRARIA', category:'Sandbox', difficulty:Difficulty.easy),
    PuzzleModel(id:'e063', answer:'SPELUNKY', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e064', answer:'CUPHEAD', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e065', answer:'CELESTE', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e066', answer:'HOLLOW KNIGHT', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e067', answer:'UNDERTALE', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e068', answer:'UNDERTALE', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e069', answer:'PORTAL', category:'Puzzle', difficulty:Difficulty.easy),
    PuzzleModel(id:'e070', answer:'HALF LIFE', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e071', answer:'LEFT FOR DEAD', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e072', answer:'TEAM FORTRESS', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e073', answer:'RUST', category:'Survival', difficulty:Difficulty.easy),
    PuzzleModel(id:'e074', answer:'ARK', category:'Survival', difficulty:Difficulty.easy),
    PuzzleModel(id:'e075', answer:'SUBNAUTICA', category:'Survival', difficulty:Difficulty.easy),
    PuzzleModel(id:'e076', answer:'FROSTPUNK', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e077', answer:'CIVILIZATION', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e078', answer:'AGE OF EMPIRES', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e079', answer:'COMMAND AND CONQUER', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e080', answer:'TOTAL WAR', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e081', answer:'SOLITAIRE', category:'Card Game', difficulty:Difficulty.easy),
    PuzzleModel(id:'e082', answer:'MINESWEEPER', category:'Puzzle', difficulty:Difficulty.easy),
    PuzzleModel(id:'e083', answer:'PINBALL', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e084', answer:'SPACE INVADERS', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e085', answer:'GALAGA', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e086', answer:'FROGGER', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e087', answer:'CENTIPEDE', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e088', answer:'BREAKOUT', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e089', answer:'ASTEROIDS', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e090', answer:'MISSILE COMMAND', category:'Arcade', difficulty:Difficulty.easy),
    PuzzleModel(id:'e091', answer:'CRASH BANDICOOT', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e092', answer:'SPYRO', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e093', answer:'BANJO KAZOOIE', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e094', answer:'CONKER', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e095', answer:'RAYMAN', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e096', answer:'BUBSY', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e097', answer:'BATTLETOADS', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e098', answer:'DUCKTALES', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e099', answer:'MEGAMAN', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e100', answer:'CONTRA', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e101', answer:'CASTLEVANIA', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e102', answer:'GHOSTS AND GOBLINS', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e103', answer:'DOUBLE DRAGON', category:'Fighting', difficulty:Difficulty.easy),
    PuzzleModel(id:'e104', answer:'FINAL FIGHT', category:'Fighting', difficulty:Difficulty.easy),
    PuzzleModel(id:'e105', answer:'GOLDEN AXE', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e106', answer:'STREETS OF RAGE', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e107', answer:'TURTLES IN TIME', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e108', answer:'BOMBERMAN', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e109', answer:'LEMMINGS', category:'Puzzle', difficulty:Difficulty.easy),
    PuzzleModel(id:'e110', answer:'WORMS', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e111', answer:'BRAID', category:'Puzzle', difficulty:Difficulty.easy),
    PuzzleModel(id:'e112', answer:'LIMBO', category:'Puzzle', difficulty:Difficulty.easy),
    PuzzleModel(id:'e113', answer:'INSIDE', category:'Puzzle', difficulty:Difficulty.easy),
    PuzzleModel(id:'e114', answer:'JOURNEY', category:'Adventure', difficulty:Difficulty.easy),
    PuzzleModel(id:'e115', answer:'ABZU', category:'Adventure', difficulty:Difficulty.easy),
    PuzzleModel(id:'e116', answer:'FLOWER', category:'Casual', difficulty:Difficulty.easy),
    PuzzleModel(id:'e117', answer:'FLOW', category:'Casual', difficulty:Difficulty.easy),
    PuzzleModel(id:'e118', answer:'MINECRAFT DUNGEONS', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e119', answer:'LEGENDS OF ZELDA', category:'Adventure', difficulty:Difficulty.easy),
    PuzzleModel(id:'e120', answer:'SUPER MARIO', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e121', answer:'MARIO PARTY', category:'Party', difficulty:Difficulty.easy),
    PuzzleModel(id:'e122', answer:'SMASH BROS', category:'Fighting', difficulty:Difficulty.easy),
    PuzzleModel(id:'e123', answer:'ARMS', category:'Fighting', difficulty:Difficulty.easy),
    PuzzleModel(id:'e124', answer:'MARIO GALAXY', category:'Platformer', difficulty:Difficulty.easy),
    PuzzleModel(id:'e125', answer:'PIKMIN', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e126', answer:'STAR FOX', category:'Shooter', difficulty:Difficulty.easy),
    PuzzleModel(id:'e127', answer:'F ZERO', category:'Racing', difficulty:Difficulty.easy),
    PuzzleModel(id:'e128', answer:'FIRE EMBLEM', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e129', answer:'XENOBLADE', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e130', answer:'METROID', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e131', answer:'EARTHBOUND', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e132', answer:'MOTHER', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e133', answer:'ADVANCE WARS', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e134', answer:'GOLDEN SUN', category:'RPG', difficulty:Difficulty.easy),
    PuzzleModel(id:'e135', answer:'POKEMON GO', category:'Mobile', difficulty:Difficulty.easy),
    PuzzleModel(id:'e136', answer:'WORDSCAPES', category:'Puzzle', difficulty:Difficulty.easy),
    PuzzleModel(id:'e137', answer:'SUBWAY SURFERS', category:'Mobile', difficulty:Difficulty.easy),
    PuzzleModel(id:'e138', answer:'TEMPLE RUN', category:'Mobile', difficulty:Difficulty.easy),
    PuzzleModel(id:'e139', answer:'FLAPPY BIRD', category:'Mobile', difficulty:Difficulty.easy),
    PuzzleModel(id:'e140', answer:'FRUIT NINJA', category:'Mobile', difficulty:Difficulty.easy),
    PuzzleModel(id:'e141', answer:'CUT THE ROPE', category:'Puzzle', difficulty:Difficulty.easy),
    PuzzleModel(id:'e142', answer:'DOODLE JUMP', category:'Mobile', difficulty:Difficulty.easy),
    PuzzleModel(id:'e143', answer:'JETPACK JOYRIDE', category:'Mobile', difficulty:Difficulty.easy),
    PuzzleModel(id:'e144', answer:'GEOMETRY DASH', category:'Mobile', difficulty:Difficulty.easy),
    PuzzleModel(id:'e145', answer:'CLASH ROYALE', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e146', answer:'BRAWL STARS', category:'Action', difficulty:Difficulty.easy),
    PuzzleModel(id:'e147', answer:'HAY DAY', category:'Simulation', difficulty:Difficulty.easy),
    PuzzleModel(id:'e148', answer:'BOOM BEACH', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e149', answer:'CLASH OF KINGS', category:'Strategy', difficulty:Difficulty.easy),
    PuzzleModel(id:'e150', answer:'RISE OF KINGDOMS', category:'Strategy', difficulty:Difficulty.easy),
  ];

  static const List<PuzzleModel> mediumPuzzles = [
    PuzzleModel(id:'m001', answer:'DARK SOULS', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m002', answer:'ELDEN RING', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m003', answer:'BLOODBORNE', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m004', answer:'SEKIRO', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m005', answer:'DEMON SOULS', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m006', answer:'GHOST OF TSUSHIMA', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m007', answer:'GOD OF WAR', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m008', answer:'SPIDER MAN', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m009', answer:'HORIZON ZERO DAWN', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m010', answer:'ASSASSINS CREED', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m011', answer:'BATMAN ARKHAM', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m012', answer:'MASS EFFECT', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m013', answer:'DRAGON AGE', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m014', answer:'FINAL FANTASY', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m015', answer:'KINGDOM HEARTS', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m016', answer:'PERSONA', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m017', answer:'DRAGON QUEST', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m018', answer:'TALES OF BERSERIA', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m019', answer:'NI NO KUNI', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m020', answer:'XENOGEARS', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m021', answer:'CHRONO TRIGGER', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m022', answer:'SECRET OF MANA', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m023', answer:'BALDURS GATE', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m024', answer:'NEVERWINTER NIGHTS', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m025', answer:'DIVINITY ORIGINAL SIN', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m026', answer:'PATHFINDER', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m027', answer:'PILLARS OF ETERNITY', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m028', answer:'TYRANNY', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m029', answer:'TORMENT', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m030', answer:'WASTELAND', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m031', answer:'BIOSHOCK', category:'Shooter', difficulty:Difficulty.medium),
    PuzzleModel(id:'m032', answer:'SYSTEM SHOCK', category:'Shooter', difficulty:Difficulty.medium),
    PuzzleModel(id:'m033', answer:'DEUS EX', category:'Stealth', difficulty:Difficulty.medium),
    PuzzleModel(id:'m034', answer:'DISHONORED', category:'Stealth', difficulty:Difficulty.medium),
    PuzzleModel(id:'m035', answer:'PREY', category:'Shooter', difficulty:Difficulty.medium),
    PuzzleModel(id:'m036', answer:'TITANFALL', category:'Shooter', difficulty:Difficulty.medium),
    PuzzleModel(id:'m037', answer:'DESTINY', category:'Shooter', difficulty:Difficulty.medium),
    PuzzleModel(id:'m038', answer:'BORDERLANDS', category:'Shooter', difficulty:Difficulty.medium),
    PuzzleModel(id:'m039', answer:'RAGE', category:'Shooter', difficulty:Difficulty.medium),
    PuzzleModel(id:'m040', answer:'WOLFENSTEIN', category:'Shooter', difficulty:Difficulty.medium),
    PuzzleModel(id:'m041', answer:'DEAD SPACE', category:'Horror', difficulty:Difficulty.medium),
    PuzzleModel(id:'m042', answer:'ALIEN ISOLATION', category:'Horror', difficulty:Difficulty.medium),
    PuzzleModel(id:'m043', answer:'OUTLAST', category:'Horror', difficulty:Difficulty.medium),
    PuzzleModel(id:'m044', answer:'AMNESIA', category:'Horror', difficulty:Difficulty.medium),
    PuzzleModel(id:'m045', answer:'SOMA', category:'Horror', difficulty:Difficulty.medium),
    PuzzleModel(id:'m046', answer:'LITTLE NIGHTMARES', category:'Horror', difficulty:Difficulty.medium),
    PuzzleModel(id:'m047', answer:'FIVE NIGHTS AT FREDDYS', category:'Horror', difficulty:Difficulty.medium),
    PuzzleModel(id:'m048', answer:'UNTIL DAWN', category:'Horror', difficulty:Difficulty.medium),
    PuzzleModel(id:'m049', answer:'LAYERS OF FEAR', category:'Horror', difficulty:Difficulty.medium),
    PuzzleModel(id:'m050', answer:'OBSERVER', category:'Horror', difficulty:Difficulty.medium),
    PuzzleModel(id:'m051', answer:'HADES', category:'Roguelike', difficulty:Difficulty.medium),
    PuzzleModel(id:'m052', answer:'DEAD CELLS', category:'Roguelike', difficulty:Difficulty.medium),
    PuzzleModel(id:'m053', answer:'ENTER THE GUNGEON', category:'Roguelike', difficulty:Difficulty.medium),
    PuzzleModel(id:'m054', answer:'BINDING OF ISAAC', category:'Roguelike', difficulty:Difficulty.medium),
    PuzzleModel(id:'m055', answer:'RISK OF RAIN', category:'Roguelike', difficulty:Difficulty.medium),
    PuzzleModel(id:'m056', answer:'SLAY THE SPIRE', category:'Card Game', difficulty:Difficulty.medium),
    PuzzleModel(id:'m057', answer:'MONSTER TRAIN', category:'Card Game', difficulty:Difficulty.medium),
    PuzzleModel(id:'m058', answer:'INSCRYPTION', category:'Card Game', difficulty:Difficulty.medium),
    PuzzleModel(id:'m059', answer:'GWENT', category:'Card Game', difficulty:Difficulty.medium),
    PuzzleModel(id:'m060', answer:'MAGIC THE GATHERING', category:'Card Game', difficulty:Difficulty.medium),
    PuzzleModel(id:'m061', answer:'UNCHARTED', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m062', answer:'LAST OF US', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m063', answer:'TOMB RAIDER', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m064', answer:'INDIANA JONES', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m065', answer:'ALAN WAKE', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m066', answer:'CONTROL', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m067', answer:'QUANTUM BREAK', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m068', answer:'MAX PAYNE', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m069', answer:'HITMAN', category:'Stealth', difficulty:Difficulty.medium),
    PuzzleModel(id:'m070', answer:'SPLINTER CELL', category:'Stealth', difficulty:Difficulty.medium),
    PuzzleModel(id:'m071', answer:'STAR WARS JEDI', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m072', answer:'KNIGHTS OF THE OLD REPUBLIC', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m073', answer:'THE OLD REPUBLIC', category:'MMO', difficulty:Difficulty.medium),
    PuzzleModel(id:'m074', answer:'WORLD OF WARCRAFT', category:'MMO', difficulty:Difficulty.medium),
    PuzzleModel(id:'m075', answer:'FINAL FANTASY XIV', category:'MMO', difficulty:Difficulty.medium),
    PuzzleModel(id:'m076', answer:'GUILD WARS', category:'MMO', difficulty:Difficulty.medium),
    PuzzleModel(id:'m077', answer:'ELDER SCROLLS ONLINE', category:'MMO', difficulty:Difficulty.medium),
    PuzzleModel(id:'m078', answer:'LOST ARK', category:'MMO', difficulty:Difficulty.medium),
    PuzzleModel(id:'m079', answer:'BLACK DESERT', category:'MMO', difficulty:Difficulty.medium),
    PuzzleModel(id:'m080', answer:'NEW WORLD', category:'MMO', difficulty:Difficulty.medium),
    PuzzleModel(id:'m081', answer:'GENSHIN IMPACT', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m082', answer:'STAR RAIL', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m083', answer:'ZENLESS ZONE ZERO', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m084', answer:'WUTHERING WAVES', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m085', answer:'TOWER OF FANTASY', category:'MMO', difficulty:Difficulty.medium),
    PuzzleModel(id:'m086', answer:'BREATH OF THE WILD', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m087', answer:'TEARS OF THE KINGDOM', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m088', answer:'LINKS AWAKENING', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m089', answer:'MAJORAS MASK', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m090', answer:'OCARINA OF TIME', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m091', answer:'WIND WAKER', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m092', answer:'TWILIGHT PRINCESS', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m093', answer:'SKYWARD SWORD', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m094', answer:'A LINK TO THE PAST', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m095', answer:'SPIRIT TRACKS', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m096', answer:'METROID PRIME', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m097', answer:'SUPER METROID', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m098', answer:'METROID DREAD', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m099', answer:'AXIOM VERGE', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m100', answer:'ORI AND THE BLIND FOREST', category:'Platformer', difficulty:Difficulty.medium),
    PuzzleModel(id:'m101', answer:'HOLLOW KNIGHT SILKSONG', category:'Platformer', difficulty:Difficulty.medium),
    PuzzleModel(id:'m102', answer:'ENDER LILIES', category:'Platformer', difficulty:Difficulty.medium),
    PuzzleModel(id:'m103', answer:'SALT AND SANCTUARY', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m104', answer:'LORDS OF THE FALLEN', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m105', answer:'CODE VEIN', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m106', answer:'NIOH', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m107', answer:'LIES OF P', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m108', answer:'STAR OCEAN', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m109', answer:'TALES OF ARISE', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m110', answer:'YAKUZA', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m111', answer:'JUDGMENT', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m112', answer:'LOST JUDGMENT', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m113', answer:'SHENMUE', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m114', answer:'DEATH STRANDING', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m115', answer:'METAL GEAR SOLID', category:'Stealth', difficulty:Difficulty.medium),
    PuzzleModel(id:'m116', answer:'ZONE OF THE ENDERS', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m117', answer:'BAYONETTA', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m118', answer:'DEVIL MAY CRY', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m119', answer:'DANTE INFERNO', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m120', answer:'GOD OF WAR RAGNAROK', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m121', answer:'DAYS GONE', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m122', answer:'HORIZON FORBIDDEN WEST', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m123', answer:'RETURNAL', category:'Roguelike', difficulty:Difficulty.medium),
    PuzzleModel(id:'m124', answer:'RATCHET AND CLANK', category:'Platformer', difficulty:Difficulty.medium),
    PuzzleModel(id:'m125', answer:'ASTRO BOT', category:'Platformer', difficulty:Difficulty.medium),
    PuzzleModel(id:'m126', answer:'DEMONS SOULS REMAKE', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m127', answer:'SACKBOY', category:'Platformer', difficulty:Difficulty.medium),
    PuzzleModel(id:'m128', answer:'DESTRUCTION ALL STARS', category:'Racing', difficulty:Difficulty.medium),
    PuzzleModel(id:'m129', answer:'NIER AUTOMATA', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m130', answer:'DRAKENGARD', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m131', answer:'XENOSAGA', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m132', answer:'STAR OCEAN THE SECOND STORY', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m133', answer:'VALKYRIE PROFILE', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m134', answer:'RESONANCE OF FATE', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m135', answer:'INFINITE UNDISCOVERY', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m136', answer:'BLUE DRAGON', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m137', answer:'LOST ODYSSEY', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m138', answer:'FABLE', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m139', answer:'JADE EMPIRE', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m140', answer:'KOTOR', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m141', answer:'STAR WARS FALLEN ORDER', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m142', answer:'GUARDIANS OF THE GALAXY', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m143', answer:'AVENGERS', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m144', answer:'GOTHAM KNIGHTS', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m145', answer:'SUICIDE SQUAD', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m146', answer:'INSOMNIAC WOLVERINE', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m147', answer:'MORTAL KOMBAT', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m148', answer:'INJUSTICE', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m149', answer:'SOUL CALIBUR', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m150', answer:'VIRTUA FIGHTER', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m151', answer:'KING OF FIGHTERS', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m152', answer:'GUILTY GEAR', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m153', answer:'BLAZBLUE', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m154', answer:'UNDER NIGHT IN BIRTH', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m155', answer:'GRANBLUE FANTASY VERSUS', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m156', answer:'DRAGON BALL FIGHTERZ', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m157', answer:'NARUTO STORM', category:'Fighting', difficulty:Difficulty.medium),
    PuzzleModel(id:'m158', answer:'ONE PIECE PIRATE WARRIORS', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m159', answer:'BLEACH SOUL RESURRECCION', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m160', answer:'ATTACK ON TITAN', category:'Action', difficulty:Difficulty.medium),
    PuzzleModel(id:'m161', answer:'MONSTER HUNTER', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m162', answer:'MONSTER HUNTER WORLD', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m163', answer:'MONSTER HUNTER RISE', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m164', answer:'TOUKIDEN', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m165', answer:'GOD EATER', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m166', answer:'FREEDOM WARS', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m167', answer:'SOUL SACRIFICE', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m168', answer:'DAUNTLESS', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m169', answer:'WILD HEARTS', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m170', answer:'STRANGER OF PARADISE', category:'Action RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m171', answer:'TINYKIN', category:'Platformer', difficulty:Difficulty.medium),
    PuzzleModel(id:'m172', answer:'PSYCHONAUTS', category:'Platformer', difficulty:Difficulty.medium),
    PuzzleModel(id:'m173', answer:'A HAT IN TIME', category:'Platformer', difficulty:Difficulty.medium),
    PuzzleModel(id:'m174', answer:'YO KAI WATCH', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m175', answer:'DIGIMON WORLD', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m176', answer:'TEMTEM', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m177', answer:'COROMON', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m178', answer:'CASSETTE BEASTS', category:'RPG', difficulty:Difficulty.medium),
    PuzzleModel(id:'m179', answer:'BUGSNAX', category:'Adventure', difficulty:Difficulty.medium),
    PuzzleModel(id:'m180', answer:'ISLANDERS', category:'Strategy', difficulty:Difficulty.medium),
    PuzzleModel(id:'m181', answer:'TOWNSCAPER', category:'Casual', difficulty:Difficulty.medium),
    PuzzleModel(id:'m182', answer:'DORFROMANTIK', category:'Puzzle', difficulty:Difficulty.medium),
    PuzzleModel(id:'m183', answer:'KAIROSOFT', category:'Simulation', difficulty:Difficulty.medium),
    PuzzleModel(id:'m184', answer:'TWO POINT HOSPITAL', category:'Simulation', difficulty:Difficulty.medium),
    PuzzleModel(id:'m185', answer:'PLANET ZOO', category:'Simulation', difficulty:Difficulty.medium),
    PuzzleModel(id:'m186', answer:'JURASSIC WORLD EVOLUTION', category:'Simulation', difficulty:Difficulty.medium),
    PuzzleModel(id:'m187', answer:'ROLLERCOASTER TYCOON', category:'Simulation', difficulty:Difficulty.medium),
    PuzzleModel(id:'m188', answer:'THEME HOSPITAL', category:'Simulation', difficulty:Difficulty.medium),
    PuzzleModel(id:'m189', answer:'CITIES SKYLINES', category:'Simulation', difficulty:Difficulty.medium),
    PuzzleModel(id:'m190', answer:'SIMCITY', category:'Simulation', difficulty:Difficulty.medium),
    PuzzleModel(id:'m191', answer:'TROPICO', category:'Strategy', difficulty:Difficulty.medium),
    PuzzleModel(id:'m192', answer:'ANNO', category:'Strategy', difficulty:Difficulty.medium),
    PuzzleModel(id:'m193', answer:'SETTLERS', category:'Strategy', difficulty:Difficulty.medium),
    PuzzleModel(id:'m194', answer:'BANISHED', category:'Strategy', difficulty:Difficulty.medium),
    PuzzleModel(id:'m195', answer:'RIMWORLD', category:'Strategy', difficulty:Difficulty.medium),
    PuzzleModel(id:'m196', answer:'DWARF FORTRESS', category:'Strategy', difficulty:Difficulty.medium),
    PuzzleModel(id:'m197', answer:'OXYGEN NOT INCLUDED', category:'Strategy', difficulty:Difficulty.medium),
    PuzzleModel(id:'m198', answer:'FACTORIO', category:'Strategy', difficulty:Difficulty.medium),
    PuzzleModel(id:'m199', answer:'SATISFACTORY', category:'Sandbox', difficulty:Difficulty.medium),
    PuzzleModel(id:'m200', answer:'DYSON SPHERE PROGRAM', category:'Strategy', difficulty:Difficulty.medium),
  ];

  static const List<PuzzleModel> hardPuzzles = [
    PuzzleModel(id:'h001', answer:'PLANESCAPE TORMENT', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h002', answer:'BALDURS GATE THREE', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h003', answer:'NEVERWINTER NIGHTS TWO', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h004', answer:'DISCO ELYSIUM', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h005', answer:'PENTIMENT', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h006', answer:'OUTER WILDS', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h007', answer:'RETURN OF THE OBRA DINN', category:'Puzzle', difficulty:Difficulty.hard),
    PuzzleModel(id:'h008', answer:'OUTER WORLDS', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h009', answer:'WASTELAND THREE', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h010', answer:'COLONY SHIP', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h011', answer:'SHADOWRUN RETURNS', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h012', answer:'CYBERPUNK FORTY SEVENTY SEVEN', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h013', answer:'STAR WARS THE FORCE UNLEASHED', category:'Action', difficulty:Difficulty.hard),
    PuzzleModel(id:'h014', answer:'KNIGHTS OF THE OLD REPUBLIC TWO', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h015', answer:'JEDI SURVIVOR', category:'Action', difficulty:Difficulty.hard),
    PuzzleModel(id:'h016', answer:'GHOST OF TSUSHIMA IKI ISLAND', category:'Action', difficulty:Difficulty.hard),
    PuzzleModel(id:'h017', answer:'HORIZON CALL OF THE MOUNTAIN', category:'Action', difficulty:Difficulty.hard),
    PuzzleModel(id:'h018', answer:'DEATH LOOP', category:'Shooter', difficulty:Difficulty.hard),
    PuzzleModel(id:'h019', answer:'WEIRD WEST', category:'Action', difficulty:Difficulty.hard),
    PuzzleModel(id:'h020', answer:'DEATHSMILES', category:'Shooter', difficulty:Difficulty.hard),
    PuzzleModel(id:'h021', answer:'ESPGALUDA', category:'Shooter', difficulty:Difficulty.hard),
    PuzzleModel(id:'h022', answer:'IKARUGA', category:'Shooter', difficulty:Difficulty.hard),
    PuzzleModel(id:'h023', answer:'CAVE STORY PLUS', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h024', answer:'KERO BLASTER', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h025', answer:'SHOVEL KNIGHT KING OF CARDS', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h026', answer:'MONSTER BOY AND THE CURSED KINGDOM', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h027', answer:'SHANTAE HALF GENIE HERO', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h028', answer:'FREEDOM PLANET', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h029', answer:'RIVALS OF AETHER', category:'Fighting', difficulty:Difficulty.hard),
    PuzzleModel(id:'h030', answer:'WINDJAMMERS', category:'Sports', difficulty:Difficulty.hard),
    PuzzleModel(id:'h031', answer:'NIDHOGG', category:'Fighting', difficulty:Difficulty.hard),
    PuzzleModel(id:'h032', answer:'LETHAL LEAGUE BLAZE', category:'Sports', difficulty:Difficulty.hard),
    PuzzleModel(id:'h033', answer:'SKULLGIRLS', category:'Fighting', difficulty:Difficulty.hard),
    PuzzleModel(id:'h034', answer:'THEM FIGHTING HERDS', category:'Fighting', difficulty:Difficulty.hard),
    PuzzleModel(id:'h035', answer:'FANTASY STRIKE', category:'Fighting', difficulty:Difficulty.hard),
    PuzzleModel(id:'h036', answer:'POCKET RUMBLE', category:'Fighting', difficulty:Difficulty.hard),
    PuzzleModel(id:'h037', answer:'DIVINE KNOCKOUT', category:'Fighting', difficulty:Difficulty.hard),
    PuzzleModel(id:'h038', answer:'NICK ALL STAR BRAWL', category:'Fighting', difficulty:Difficulty.hard),
    PuzzleModel(id:'h039', answer:'MULTIVERSUS', category:'Fighting', difficulty:Difficulty.hard),
    PuzzleModel(id:'h040', answer:'BRAWLHALLA', category:'Fighting', difficulty:Difficulty.hard),
    PuzzleModel(id:'h041', answer:'NOITA', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h042', answer:'CAVES OF QUD', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h043', answer:'NETHACK', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h044', answer:'ANGBAND', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h045', answer:'DUNGEON CRAWL STONE SOUP', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h046', answer:'ANCIENT DOMAINS OF MYSTERY', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h047', answer:'TOME TALES OF MAJ EYAL', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h048', answer:'INCURSION THE ROGUELIKE', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h049', answer:'LEGEND OF GRIMROCK', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h050', answer:'WIZARDRY EIGHT', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h051', answer:'ETRIAN ODYSSEY', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h052', answer:'ELMINAGE GOTHIC', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h053', answer:'CLASS OF HEROES', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h054', answer:'MONSTER MAZE', category:'Puzzle', difficulty:Difficulty.hard),
    PuzzleModel(id:'h055', answer:'GEPETTO', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h056', answer:'OPUS MAGNUM', category:'Puzzle', difficulty:Difficulty.hard),
    PuzzleModel(id:'h057', answer:'SPACECHEM', category:'Puzzle', difficulty:Difficulty.hard),
    PuzzleModel(id:'h058', answer:'INFINIFACTORY', category:'Puzzle', difficulty:Difficulty.hard),
    PuzzleModel(id:'h059', answer:'SHENZHEN IO', category:'Puzzle', difficulty:Difficulty.hard),
    PuzzleModel(id:'h060', answer:'EXAPUNKS', category:'Puzzle', difficulty:Difficulty.hard),
    PuzzleModel(id:'h061', answer:'HACKNET', category:'Puzzle', difficulty:Difficulty.hard),
    PuzzleModel(id:'h062', answer:'ZACHATRONICS SOLITAIRE COLLECTION', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h063', answer:'CULTIST SIMULATOR', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h064', answer:'BOOK OF HOURS', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h065', answer:'ELDRITCH HORROR', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h066', answer:'TABLETOP SIMULATOR', category:'Casual', difficulty:Difficulty.hard),
    PuzzleModel(id:'h067', answer:'ARMELLO', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h068', answer:'FAERIA', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h069', answer:'ARTIFACT', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h070', answer:'MINION MASTERS', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h071', answer:'TOTAL ANNIHILATION', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h072', answer:'SUPREME COMMANDER', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h073', answer:'PLANETARY ANNIHILATION', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h074', answer:'ASHES OF THE SINGULARITY', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h075', answer:'ENDGAME SINGULARITY', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h076', answer:'HOMEWORLD', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h077', answer:'SINS OF A SOLAR EMPIRE', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h078', answer:'DISTANT WORLDS', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h079', answer:'STELLARIS', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h080', answer:'ENDLESS SPACE', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h081', answer:'AURORA FOUR X', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h082', answer:'MASTER OF ORION', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h083', answer:'GALACTIC CIVILIZATIONS', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h084', answer:'STAR RULER', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h085', answer:'STARS IN SHADOW', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h086', answer:'ENDLESS LEGEND', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h087', answer:'FALLEN ENCHANTRESS', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h088', answer:'WARLOCK MASTER OF THE ARCANE', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h089', answer:'HEROES OF MIGHT AND MAGIC', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h090', answer:'KING BOUNTY WARRIORS', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h091', answer:'MIGHT AND MAGIC', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h092', answer:'ULTIMA UNDERWORLD', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h093', answer:'ARCANIUM RISE OF AKHAN', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h094', answer:'STONE STORY RPG', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h095', answer:'WILDERMYTH', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h096', answer:'GORDIAN QUEST', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h097', answer:'KNIGHTS IN TIGHT SPACES', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h098', answer:'COBALT CORE', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h099', answer:'ACROSS THE OBELISK', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h100', answer:'VAULT OF THE VOID', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h101', answer:'RATROPOLIS', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h102', answer:'DICEY DUNGEONS', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h103', answer:'LUCK BE A LANDLORD', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h104', answer:'PEGLIN', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h105', answer:'SHOTGUN KING', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h106', answer:'SLICE AND DICE', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h107', answer:'LOOP HERO', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h108', answer:'ROGUE LEGACY', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h109', answer:'CURSE OF THE DEAD GODS', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h110', answer:'RAVENSWATCH', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h111', answer:'VAMPIRE SURVIVORS', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h112', answer:'BROTATO', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h113', answer:'HOLOCURE', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h114', answer:'HALLS OF TORMENT', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h115', answer:'NOMAD SURVIVAL', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h116', answer:'SOULSTONE SURVIVORS', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h117', answer:'DEEP ROCK GALACTIC SURVIVOR', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h118', answer:'MINISHOOT ADVENTURES', category:'Shooter', difficulty:Difficulty.hard),
    PuzzleModel(id:'h119', answer:'BONERAISER MINIONS', category:'Roguelike', difficulty:Difficulty.hard),
    PuzzleModel(id:'h120', answer:'THRONEFALL', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h121', answer:'STACKLANDS', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h122', answer:'GOURDLETS', category:'Casual', difficulty:Difficulty.hard),
    PuzzleModel(id:'h123', answer:'SIGNS OF THE SOJOURNER', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h124', answer:'NOWHERE PROPHET', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h125', answer:'WILDFROST', category:'Card Game', difficulty:Difficulty.hard),
    PuzzleModel(id:'h126', answer:'LOST IN RANDOM', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h127', answer:'ODDWORLD INHABITANTS', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h128', answer:'PRINCE OF PERSIA LOST CROWN', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h129', answer:'ULTROS', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h130', answer:'PEPPER GRINDER', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h131', answer:'WARIO WARE INC', category:'Party', difficulty:Difficulty.hard),
    PuzzleModel(id:'h132', answer:'CHIBI ROBO PLUG INTO ADVENTURE', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h133', answer:'LITTLE KING STORY', category:'Strategy', difficulty:Difficulty.hard),
    PuzzleModel(id:'h134', answer:'ZACK AND WIKI', category:'Puzzle', difficulty:Difficulty.hard),
    PuzzleModel(id:'h135', answer:'DEWEY ADVENTURE', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h136', answer:'LOST IN SHADOW', category:'Platformer', difficulty:Difficulty.hard),
    PuzzleModel(id:'h137', answer:'FRAGILE DREAMS FAREWELL RUINS', category:'RPG', difficulty:Difficulty.hard),
    PuzzleModel(id:'h138', answer:'DISASTER DAY OF CRISIS', category:'Action', difficulty:Difficulty.hard),
    PuzzleModel(id:'h139', answer:'CAPTAIN RAINBOW', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h140', answer:'ANOTHER CODE TWO MEMORIES', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h141', answer:'TRACE MEMORY', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h142', answer:'HOTEL DUSK ROOM TWO FIFTEEN', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h143', answer:'LAST WINDOW SECRET OF CAPE WEST', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h144', answer:'PHOENIX WRIGHT ACE ATTORNEY', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h145', answer:'PROFESSOR LAYTON', category:'Puzzle', difficulty:Difficulty.hard),
    PuzzleModel(id:'h146', answer:'NINE HOURS NINE PERSONS NINE DOORS', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h147', answer:'VIRTUE LAST REWARD', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h148', answer:'DANGANRONPA', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h149', answer:'AI SOMNIUM FILES', category:'Adventure', difficulty:Difficulty.hard),
    PuzzleModel(id:'h150', answer:'RAGING LOOP', category:'Adventure', difficulty:Difficulty.hard),
  ];

  static List<PuzzleModel> forDifficulty(Difficulty d) {
    switch (d) {
      case Difficulty.easy:   return easyPuzzles;
      case Difficulty.medium: return mediumPuzzles;
      case Difficulty.hard:   return hardPuzzles;
    }
  }

  static PuzzleModel? getNext(Difficulty d, Set<String> solvedIds) {
    final pool = forDifficulty(d).where((p) => !solvedIds.contains(p.id)).toList();
    if (pool.isEmpty) return null;
    pool.shuffle(Random());
    return pool.first;
  }
}
