import '../../data/models/puzzle_model.dart';

/// Turkish puzzle database — 170+ puzzles across all difficulties.
class PuzzlesTr {
  PuzzlesTr._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('tr_e001', 'ELMA', 'Meyveler'),
    _p('tr_e002', 'ARMUT', 'Meyveler'),
    _p('tr_e003', 'PORTAKAL', 'Meyveler'),
    _p('tr_e004', 'MANGO', 'Meyveler'),
    _p('tr_e005', 'KIRAZ', 'Meyveler'),
    _p('tr_e006', 'KARPUZ', 'Meyveler'),
    _p('tr_e007', 'KAVUN', 'Meyveler'),
    _p('tr_e008', 'ERIK', 'Meyveler'),
    _p('tr_e009', 'INCIR', 'Meyveler'),
    _p('tr_e010', 'UZUM', 'Meyveler'),
    _p('tr_e011', 'KEDI', 'Hayvanlar'),
    _p('tr_e012', 'KOPEK', 'Hayvanlar'),
    _p('tr_e013', 'ASLAN', 'Hayvanlar'),
    _p('tr_e014', 'KAPLAN', 'Hayvanlar'),
    _p('tr_e015', 'TAVUK', 'Hayvanlar'),
    _p('tr_e016', 'KARTAL', 'Hayvanlar'),
    _p('tr_e017', 'BALIK', 'Hayvanlar'),
    _p('tr_e018', 'ARABA', 'Tasitlar'),
    _p('tr_e019', 'TREN', 'Tasitlar'),
    _p('tr_e020', 'GEMI', 'Tasitlar'),
    _p('tr_e021', 'BULUT', 'Doga'),
    _p('tr_e022', 'YILDIZ', 'Doga'),
    _p('tr_e023', 'DENIZ', 'Doga'),
    _p('tr_e024', 'ORMAN', 'Doga'),
    _p('tr_e025', 'NEHIR', 'Doga'),
    _p('tr_e026', 'DAGLAR', 'Doga'),
    _p('tr_e027', 'CIMEN', 'Doga'),
    _p('tr_e028', 'CICEK', 'Doga'),
    _p('tr_e029', 'TOPRAK', 'Doga'),
    _p('tr_e030', 'HAVA', 'Doga'),
    _p('tr_e031', 'MASA', 'Mobilya'),
    _p('tr_e032', 'SANDALYE', 'Mobilya'),
    _p('tr_e033', 'YATAK', 'Mobilya'),
    _p('tr_e034', 'DOLAP', 'Mobilya'),
    _p('tr_e035', 'KOLTUK', 'Mobilya'),
    _p('tr_e036', 'EKMEK', 'Yiyecekler'),
    _p('tr_e037', 'PEYNIR', 'Yiyecekler'),
    _p('tr_e038', 'YUMURTA', 'Yiyecekler'),
    _p('tr_e039', 'PILAV', 'Yiyecekler'),
    _p('tr_e040', 'CORBA', 'Yiyecekler'),
    _p('tr_e041', 'KITAP', 'Nesneler'),
    _p('tr_e042', 'KALEM', 'Nesneler'),
    _p('tr_e043', 'SAAT', 'Nesneler'),
    _p('tr_e044', 'AYNA', 'Nesneler'),
    _p('tr_e045', 'KAPAK', 'Nesneler'),
    _p('tr_e046', 'OKUL', 'Yerler'),
    _p('tr_e047', 'PARK', 'Yerler'),
    _p('tr_e048', 'BAHCE', 'Yerler'),
    _p('tr_e049', 'CADDE', 'Yerler'),
    _p('tr_e050', 'KULE', 'Yerler'),
    _p('tr_e051', 'RENK', 'Soyut'),
    _p('tr_e052', 'SIHIR', 'Fantezi'),
    _p('tr_e053', 'RUZGAR', 'Doga'),
    _p('tr_e054', 'GUMUS', 'Metaller'),
    _p('tr_e055', 'ALTIN', 'Metaller'),
    _p('tr_e056', 'DEMIR', 'Metaller'),
    _p('tr_e057', 'BAKIR', 'Metaller'),
    _p('tr_e058', 'IPEK', 'Kumaslar'),
    _p('tr_e059', 'PAMUK', 'Kumaslar'),
    _p('tr_e060', 'YAGMUR', 'Hava'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('tr_m001', 'KELEBEK', 'Hayvanlar'),
    _pm('tr_m002', 'PENGUEN', 'Hayvanlar'),
    _pm('tr_m003', 'ZURAFA', 'Hayvanlar'),
    _pm('tr_m004', 'TIMSAH', 'Hayvanlar'),
    _pm('tr_m005', 'FLAMINGO', 'Hayvanlar'),
    _pm('tr_m006', 'PAPAGAN', 'Hayvanlar'),
    _pm('tr_m007', 'YUNUS', 'Hayvanlar'),
    _pm('tr_m008', 'SARAY', 'Yerler'),
    _pm('tr_m009', 'CAMI', 'Yerler'),
    _pm('tr_m010', 'KOPRU', 'Yerler'),
    _pm('tr_m011', 'LIMAN', 'Yerler'),
    _pm('tr_m012', 'KALE', 'Yerler'),
    _pm('tr_m013', 'MUZIK', 'Sanat'),
    _pm('tr_m014', 'RESIM', 'Sanat'),
    _pm('tr_m015', 'HEYKEL', 'Sanat'),
    _pm('tr_m016', 'TIYATRO', 'Sanat'),
    _pm('tr_m017', 'SINEMA', 'Sanat'),
    _pm('tr_m018', 'FUTBOL', 'Sporlar'),
    _pm('tr_m019', 'BASKETBOL', 'Sporlar'),
    _pm('tr_m020', 'VOLEYBOL', 'Sporlar'),
    _pm('tr_m021', 'YUZME', 'Sporlar'),
    _pm('tr_m022', 'BOKSING', 'Sporlar'),
    _pm('tr_m023', 'GEZEGEN', 'Uzay'),
    _pm('tr_m024', 'ROKET', 'Uzay'),
    _pm('tr_m025', 'METEOR', 'Uzay'),
    _pm('tr_m026', 'GALAKSI', 'Uzay'),
    _pm('tr_m027', 'BILGISAYAR', 'Teknoloji'),
    _pm('tr_m028', 'TELEFON', 'Teknoloji'),
    _pm('tr_m029', 'TABLET', 'Teknoloji'),
    _pm('tr_m030', 'ROBOT', 'Teknoloji'),
    _pm('tr_m031', 'DEPREM', 'Doga'),
    _pm('tr_m032', 'YANARDAG', 'Doga'),
    _pm('tr_m033', 'TSUNAMI', 'Doga'),
    _pm('tr_m034', 'KASIRGA', 'Doga'),
    _pm('tr_m035', 'IKLIM', 'Doga'),
    _pm('tr_m036', 'ELMAS', 'Degerli Taslar'),
    _pm('tr_m037', 'YAKUT', 'Degerli Taslar'),
    _pm('tr_m038', 'ZUMRUT', 'Degerli Taslar'),
    _pm('tr_m039', 'SAFIR', 'Degerli Taslar'),
    _pm('tr_m040', 'AMETIST', 'Degerli Taslar'),
    _pm('tr_m041', 'CADIRCI', 'Meslekler'),
    _pm('tr_m042', 'DOKTOR', 'Meslekler'),
    _pm('tr_m043', 'MUHENDIS', 'Meslekler'),
    _pm('tr_m044', 'OGRETMEN', 'Meslekler'),
    _pm('tr_m045', 'AVUKAT', 'Meslekler'),
    _pm('tr_m046', 'HEMSIRE', 'Meslekler'),
    _pm('tr_m047', 'KAPTAN', 'Meslekler'),
    _pm('tr_m048', 'RESSAM', 'Meslekler'),
    _pm('tr_m049', 'ASKER', 'Meslekler'),
    _pm('tr_m050', 'GARSON', 'Meslekler'),
    _pm('tr_m051', 'KAHRAMAN', 'Soyut'),
    _pm('tr_m052', 'CESARET', 'Soyut'),
    _pm('tr_m053', 'OZGURLUK', 'Soyut'),
    _pm('tr_m054', 'MACERA', 'Soyut'),
    _pm('tr_m055', 'HAZINE', 'Macera'),
    _pm('tr_m056', 'PUSULA', 'Macera'),
    _pm('tr_m057', 'HARITA', 'Macera'),
    _pm('tr_m058', 'KESFET', 'Macera'),
    _pm('tr_m059', 'EFSANE', 'Fantezi'),
    _pm('tr_m060', 'BUYUCU', 'Fantezi'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('tr_h001', 'KARA ORMAN', 'Doga'),
    _ph('tr_h002', 'UZAY YOLU', 'Bilim Kurgu'),
    _ph('tr_h003', 'KUZEY YILDIZI', 'Astronomi'),
    _ph('tr_h004', 'ALTIN CAGI', 'Tarih'),
    _ph('tr_h005', 'DENIZ FENERI', 'Yerler'),
    _ph('tr_h006', 'KARA KALE', 'Fantezi'),
    _ph('tr_h007', 'BUZ DAGLARI', 'Doga'),
    _ph('tr_h008', 'AY ISIGI', 'Doga'),
    _ph('tr_h009', 'GUNES TUTULMASI', 'Astronomi'),
    _ph('tr_h010', 'KAR FIRTINASI', 'Hava'),
    _ph('tr_h011', 'ALEV TOPU', 'Fantezi'),
    _ph('tr_h012', 'KURT ADAM', 'Efsaneler'),
    _ph('tr_h013', 'ANKA KUSU', 'Mitoloji'),
    _ph('tr_h014', 'GIZLI GECIT', 'Macera'),
    _ph('tr_h015', 'HAZINE AVCI', 'Macera'),
    _ph('tr_h016', 'TAHT OYUNLARI', 'Fantezi'),
    _ph('tr_h017', 'SIS PERDESI', 'Doga'),
    _ph('tr_h018', 'GECE YARISI', 'Zaman'),
    _ph('tr_h019', 'SAMAN YOLU', 'Uzay'),
    _ph('tr_h020', 'CENNET BAHCESI', 'Mitoloji'),
    _ph('tr_h021', 'KAYIP SEHIR', 'Tarih'),
    _ph('tr_h022', 'KARA ELMAS', 'Degerli Taslar'),
    _ph('tr_h023', 'UZAK DIYAR', 'Fantezi'),
    _ph('tr_h024', 'DERIN DENIZ', 'Doga'),
    _ph('tr_h025', 'ALEV KILICI', 'Fantezi'),
    _ph('tr_h026', 'KUM SAATI', 'Nesneler'),
    _ph('tr_h027', 'YILDIZ TOZU', 'Uzay'),
    _ph('tr_h028', 'GIZLI BAHCE', 'Yerler'),
    _ph('tr_h029', 'EJDER AVI', 'Fantezi'),
    _ph('tr_h030', 'GIZEMLI ADA', 'Macera'),
    _ph('tr_h031', 'GOKKUSAGI', 'Doga'),
    _ph('tr_h032', 'SES DUVARI', 'Bilim'),
    _ph('tr_h033', 'ISIK HIZI', 'Bilim'),
    _ph('tr_h034', 'BARIS GULU', 'Soyut'),
    _ph('tr_h035', 'GIZEM KUTUSU', 'Macera'),
    _ph('tr_h036', 'FIRTINA KUSU', 'Doga'),
    _ph('tr_h037', 'CESUR YILDIZ', 'Fantezi'),
    _ph('tr_h038', 'BUYULU ORMAN', 'Fantezi'),
    _ph('tr_h039', 'ATES DIYARI', 'Fantezi'),
    _ph('tr_h040', 'KARA GEMI', 'Macera'),
    _ph('tr_h041', 'DEMIR YUMRUK', 'Aksiyon'),
    _ph('tr_h042', 'KAR KRALI', 'Fantezi'),
    _ph('tr_h043', 'ALEV OKCU', 'Fantezi'),
    _ph('tr_h044', 'YESIL VADI', 'Doga'),
    _ph('tr_h045', 'KURT KAPANI', 'Doga'),
    _ph('tr_h046', 'SEMA KAPISI', 'Fantezi'),
    _ph('tr_h047', 'KUM COLU', 'Doga'),
    _ph('tr_h048', 'AY TANRISI', 'Mitoloji'),
    _ph('tr_h049', 'BEYAZ KURT', 'Hayvanlar'),
    _ph('tr_h050', 'GECE AVCISI', 'Fantezi'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'tr',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'tr',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'tr',
      );
}
