import '../../data/models/puzzle_model.dart';

/// Italian puzzle database — 170+ puzzles across all difficulties.
class PuzzlesIt {
  PuzzlesIt._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('it_e001', 'MELA', 'Frutta'),
    _p('it_e002', 'PERA', 'Frutta'),
    _p('it_e003', 'LIMONE', 'Frutta'),
    _p('it_e004', 'ARANCIA', 'Frutta'),
    _p('it_e005', 'BANANA', 'Frutta'),
    _p('it_e006', 'CILIEGIA', 'Frutta'),
    _p('it_e007', 'MELONE', 'Frutta'),
    _p('it_e008', 'PRUGNA', 'Frutta'),
    _p('it_e009', 'FRAGOLA', 'Frutta'),
    _p('it_e010', 'PESCA', 'Frutta'),
    _p('it_e011', 'GATTO', 'Animali'),
    _p('it_e012', 'CANE', 'Animali'),
    _p('it_e013', 'CAVALLO', 'Animali'),
    _p('it_e014', 'LEONE', 'Animali'),
    _p('it_e015', 'TIGRE', 'Animali'),
    _p('it_e016', 'AQUILA', 'Animali'),
    _p('it_e017', 'SERPENTE', 'Animali'),
    _p('it_e018', 'TOPO', 'Animali'),
    _p('it_e019', 'VOLPE', 'Animali'),
    _p('it_e020', 'ORSO', 'Animali'),
    _p('it_e021', 'SEDIA', 'Mobili'),
    _p('it_e022', 'TAVOLO', 'Mobili'),
    _p('it_e023', 'LETTO', 'Mobili'),
    _p('it_e024', 'DIVANO', 'Mobili'),
    _p('it_e025', 'LAMPADA', 'Mobili'),
    _p('it_e026', 'PANE', 'Cibo'),
    _p('it_e027', 'PASTA', 'Cibo'),
    _p('it_e028', 'PIZZA', 'Cibo'),
    _p('it_e029', 'RISO', 'Cibo'),
    _p('it_e030', 'ZUPPA', 'Cibo'),
    _p('it_e031', 'NUVOLA', 'Natura'),
    _p('it_e032', 'STELLA', 'Natura'),
    _p('it_e033', 'FIUME', 'Natura'),
    _p('it_e034', 'MONTE', 'Natura'),
    _p('it_e035', 'BOSCO', 'Natura'),
    _p('it_e036', 'MARE', 'Natura'),
    _p('it_e037', 'FUOCO', 'Natura'),
    _p('it_e038', 'PIETRA', 'Natura'),
    _p('it_e039', 'VENTO', 'Natura'),
    _p('it_e040', 'PIOGGIA', 'Natura'),
    _p('it_e041', 'LIBRO', 'Oggetti'),
    _p('it_e042', 'PENNA', 'Oggetti'),
    _p('it_e043', 'CORONA', 'Oggetti'),
    _p('it_e044', 'SPADA', 'Oggetti'),
    _p('it_e045', 'SCUDO', 'Oggetti'),
    _p('it_e046', 'SCUOLA', 'Luoghi'),
    _p('it_e047', 'PORTO', 'Luoghi'),
    _p('it_e048', 'TORRE', 'Luoghi'),
    _p('it_e049', 'GIARDINO', 'Luoghi'),
    _p('it_e050', 'PIAZZA', 'Luoghi'),
    _p('it_e051', 'ARGENTO', 'Metalli'),
    _p('it_e052', 'FERRO', 'Metalli'),
    _p('it_e053', 'RAME', 'Metalli'),
    _p('it_e054', 'SETA', 'Tessuti'),
    _p('it_e055', 'COTONE', 'Tessuti'),
    _p('it_e056', 'PIANOFORTE', 'Musica'),
    _p('it_e057', 'VIOLINO', 'Musica'),
    _p('it_e058', 'FLAUTO', 'Musica'),
    _p('it_e059', 'CHITARRA', 'Musica'),
    _p('it_e060', 'SOGNO', 'Astratto'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('it_m001', 'CAVALIERE', 'Fantasia'),
    _pm('it_m002', 'DRAGO', 'Fantasia'),
    _pm('it_m003', 'MAGO', 'Fantasia'),
    _pm('it_m004', 'CASTELLO', 'Edifici'),
    _pm('it_m005', 'PALAZZO', 'Edifici'),
    _pm('it_m006', 'TEMPIO', 'Edifici'),
    _pm('it_m007', 'MUSEO', 'Edifici'),
    _pm('it_m008', 'RAZZO', 'Spazio'),
    _pm('it_m009', 'PIANETA', 'Spazio'),
    _pm('it_m010', 'GALASSIA', 'Spazio'),
    _pm('it_m011', 'CALCIO', 'Sport'),
    _pm('it_m012', 'TENNIS', 'Sport'),
    _pm('it_m013', 'NUOTO', 'Sport'),
    _pm('it_m014', 'PUGILATO', 'Sport'),
    _pm('it_m015', 'PALLAVOLO', 'Sport'),
    _pm('it_m016', 'DIAMANTE', 'Gemme'),
    _pm('it_m017', 'SMERALDO', 'Gemme'),
    _pm('it_m018', 'ZAFFIRO', 'Gemme'),
    _pm('it_m019', 'RUBINO', 'Gemme'),
    _pm('it_m020', 'AUTUNNO', 'Stagioni'),
    _pm('it_m021', 'INVERNO', 'Stagioni'),
    _pm('it_m022', 'ESTATE', 'Stagioni'),
    _pm('it_m023', 'FARFALLA', 'Animali'),
    _pm('it_m024', 'PINGUINO', 'Animali'),
    _pm('it_m025', 'GIRAFFA', 'Animali'),
    _pm('it_m026', 'DELFINO', 'Animali'),
    _pm('it_m027', 'PAPPAGALLO', 'Animali'),
    _pm('it_m028', 'FALCONE', 'Animali'),
    _pm('it_m029', 'COMPUTER', 'Tecnologia'),
    _pm('it_m030', 'ROBOT', 'Tecnologia'),
    _pm('it_m031', 'VULCANO', 'Natura'),
    _pm('it_m032', 'TERREMOTO', 'Natura'),
    _pm('it_m033', 'TEMPORALE', 'Natura'),
    _pm('it_m034', 'MEDICO', 'Mestieri'),
    _pm('it_m035', 'MAESTRO', 'Mestieri'),
    _pm('it_m036', 'SOLDATO', 'Mestieri'),
    _pm('it_m037', 'CAPITANO', 'Mestieri'),
    _pm('it_m038', 'OMBRA', 'Astratto'),
    _pm('it_m039', 'LIBERTA', 'Astratto'),
    _pm('it_m040', 'AVVENTURA', 'Astratto'),
    _pm('it_m041', 'LEGGENDA', 'Fantasia'),
    _pm('it_m042', 'BUSSOLA', 'Avventura'),
    _pm('it_m043', 'TESORO', 'Avventura'),
    _pm('it_m044', 'FENICE', 'Mitologia'),
    _pm('it_m045', 'UNICORNO', 'Mitologia'),
    _pm('it_m046', 'VICHINGO', 'Storia'),
    _pm('it_m047', 'GLADIATORE', 'Storia'),
    _pm('it_m048', 'PIRATA', 'Avventura'),
    _pm('it_m049', 'ANCORA', 'Navigazione'),
    _pm('it_m050', 'CRISTALLO', 'Minerali'),
    _pm('it_m051', 'PANTERA', 'Animali'),
    _pm('it_m052', 'ELEFANTE', 'Animali'),
    _pm('it_m053', 'CIOCCOLATA', 'Cibo'),
    _pm('it_m054', 'PEPE', 'Cibo'),
    _pm('it_m055', 'BURRO', 'Cibo'),
    _pm('it_m056', 'MARMO', 'Materiali'),
    _pm('it_m057', 'VELLUTO', 'Materiali'),
    _pm('it_m058', 'CORAGGIO', 'Astratto'),
    _pm('it_m059', 'EROE', 'Astratto'),
    _pm('it_m060', 'MAPPA', 'Avventura'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('it_h001', 'BOSCO NERO', 'Natura'),
    _ph('it_h002', 'STELLA POLARE', 'Astronomia'),
    _ph('it_h003', 'CHIARO LUNA', 'Natura'),
    _ph('it_h004', 'DRAGO FUOCO', 'Fantasia'),
    _ph('it_h005', 'CASTELLO GHIACCIO', 'Fantasia'),
    _ph('it_h006', 'VENTO TEMPESTA', 'Tempo'),
    _ph('it_h007', 'MINIERA ORO', 'Estrazione'),
    _ph('it_h008', 'FULMINE TUONO', 'Tempo'),
    _ph('it_h009', 'LUNA ARGENTO', 'Astronomia'),
    _ph('it_h010', 'FUOCO SELVAGGIO', 'Natura'),
    _ph('it_h011', 'TEMPESTA SABBIA', 'Tempo'),
    _ph('it_h012', 'MARE PROFONDO', 'Natura'),
    _ph('it_h013', 'POLVERE STELLE', 'Spazio'),
    _ph('it_h014', 'BRANCO LUPI', 'Animali'),
    _ph('it_h015', 'NAVE FANTASMA', 'Mitologia'),
    _ph('it_h016', 'TORRE OSCURA', 'Fantasia'),
    _ph('it_h017', 'BARRIERA CORALLINA', 'Natura'),
    _ph('it_h018', 'FIOCCO NEVE', 'Natura'),
    _ph('it_h019', 'PIETRA LUNA', 'Gemme'),
    _ph('it_h020', 'SPADA FIAMME', 'Fantasia'),
    _ph('it_h021', 'GRANDE MURO', 'Monumenti'),
    _ph('it_h022', 'ARCO BALENO', 'Natura'),
    _ph('it_h023', 'GROTTA CRISTALLO', 'Natura'),
    _ph('it_h024', 'PONTE PIETRA', 'Costruzioni'),
    _ph('it_h025', 'FORESTA SCURA', 'Natura'),
    _ph('it_h026', 'UCCELLO FUOCO', 'Mitologia'),
    _ph('it_h027', 'ORSO POLARE', 'Animali'),
    _ph('it_h028', 'FALCO NOTTE', 'Animali'),
    _ph('it_h029', 'DRAGO ROSSO', 'Fantasia'),
    _ph('it_h030', 'BUCO NERO', 'Spazio'),
    _ph('it_h031', 'VENTO SOLARE', 'Spazio'),
    _ph('it_h032', 'CASCATA ACQUA', 'Natura'),
    _ph('it_h033', 'CIMA MONTE', 'Natura'),
    _ph('it_h034', 'ISOLA PERDUTA', 'Avventura'),
    _ph('it_h035', 'FORZIERE TESORO', 'Avventura'),
    _ph('it_h036', 'ALBA DORATA', 'Natura'),
    _ph('it_h037', 'NOTTE STELLATA', 'Natura'),
    _ph('it_h038', 'BACCHETTA MAGICA', 'Fantasia'),
    _ph('it_h039', 'CAVALIERE DRAGO', 'Fantasia'),
    _ph('it_h040', 'MULINO VENTO', 'Costruzioni'),
    _ph('it_h041', 'FARO LUCE', 'Costruzioni'),
    _ph('it_h042', 'MARE NEBBIA', 'Natura'),
    _ph('it_h043', 'ONDA TEMPESTA', 'Natura'),
    _ph('it_h044', 'FUOCHI ARTIFICIO', 'Feste'),
    _ph('it_h045', 'GELO ETERNO', 'Natura'),
    _ph('it_h046', 'SABBIA TEMPO', 'Astratto'),
    _ph('it_h047', 'CIELO STELLATO', 'Natura'),
    _ph('it_h048', 'ROSA VENTI', 'Navigazione'),
    _ph('it_h049', 'LUPO BIANCO', 'Animali'),
    _ph('it_h050', 'CACCIATORE NOTTE', 'Fantasia'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'it',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'it',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'it',
      );
}
