import '../../data/models/puzzle_model.dart';

/// French puzzle database — 170+ puzzles across all difficulties.
class PuzzlesFr {
  PuzzlesFr._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('fr_e001', 'POMME', 'Fruits'),
    _p('fr_e002', 'POIRE', 'Fruits'),
    _p('fr_e003', 'CITRON', 'Fruits'),
    _p('fr_e004', 'ORANGE', 'Fruits'),
    _p('fr_e005', 'BANANE', 'Fruits'),
    _p('fr_e006', 'CERISE', 'Fruits'),
    _p('fr_e007', 'MELON', 'Fruits'),
    _p('fr_e008', 'PRUNE', 'Fruits'),
    _p('fr_e009', 'FRAISE', 'Fruits'),
    _p('fr_e010', 'RAISIN', 'Fruits'),
    _p('fr_e011', 'CHAT', 'Animaux'),
    _p('fr_e012', 'CHIEN', 'Animaux'),
    _p('fr_e013', 'CHEVAL', 'Animaux'),
    _p('fr_e014', 'LION', 'Animaux'),
    _p('fr_e015', 'TIGRE', 'Animaux'),
    _p('fr_e016', 'AIGLE', 'Animaux'),
    _p('fr_e017', 'SERPENT', 'Animaux'),
    _p('fr_e018', 'SOURIS', 'Animaux'),
    _p('fr_e019', 'RENARD', 'Animaux'),
    _p('fr_e020', 'OURS', 'Animaux'),
    _p('fr_e021', 'CHAISE', 'Meubles'),
    _p('fr_e022', 'TABLE', 'Meubles'),
    _p('fr_e023', 'CANAPE', 'Meubles'),
    _p('fr_e024', 'LAMPE', 'Meubles'),
    _p('fr_e025', 'MIROIR', 'Meubles'),
    _p('fr_e026', 'PAIN', 'Nourriture'),
    _p('fr_e027', 'FROMAGE', 'Nourriture'),
    _p('fr_e028', 'SOUPE', 'Nourriture'),
    _p('fr_e029', 'SALADE', 'Nourriture'),
    _p('fr_e030', 'BEURRE', 'Nourriture'),
    _p('fr_e031', 'NUAGE', 'Nature'),
    _p('fr_e032', 'ETOILE', 'Nature'),
    _p('fr_e033', 'FLEUVE', 'Nature'),
    _p('fr_e034', 'MONTAGNE', 'Nature'),
    _p('fr_e035', 'FORET', 'Nature'),
    _p('fr_e036', 'OCEAN', 'Nature'),
    _p('fr_e037', 'FLAMME', 'Nature'),
    _p('fr_e038', 'PIERRE', 'Nature'),
    _p('fr_e039', 'VENT', 'Nature'),
    _p('fr_e040', 'PLUIE', 'Nature'),
    _p('fr_e041', 'LIVRE', 'Objets'),
    _p('fr_e042', 'STYLO', 'Objets'),
    _p('fr_e043', 'COURONNE', 'Objets'),
    _p('fr_e044', 'BOUCLIER', 'Objets'),
    _p('fr_e045', 'HORLOGE', 'Objets'),
    _p('fr_e046', 'ECOLE', 'Lieux'),
    _p('fr_e047', 'PLAGE', 'Lieux'),
    _p('fr_e048', 'JARDIN', 'Lieux'),
    _p('fr_e049', 'MARCHE', 'Lieux'),
    _p('fr_e050', 'PARC', 'Lieux'),
    _p('fr_e051', 'ARGENT', 'Metaux'),
    _p('fr_e052', 'CUIVRE', 'Metaux'),
    _p('fr_e053', 'ACIER', 'Metaux'),
    _p('fr_e054', 'SOIE', 'Tissus'),
    _p('fr_e055', 'COTON', 'Tissus'),
    _p('fr_e056', 'PIANO', 'Musique'),
    _p('fr_e057', 'VIOLON', 'Musique'),
    _p('fr_e058', 'FLUTE', 'Musique'),
    _p('fr_e059', 'GUITARE', 'Musique'),
    _p('fr_e060', 'REVE', 'Abstrait'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('fr_m001', 'CHEVALIER', 'Fantaisie'),
    _pm('fr_m002', 'DRAGON', 'Fantaisie'),
    _pm('fr_m003', 'SORCIER', 'Fantaisie'),
    _pm('fr_m004', 'CHATEAU', 'Batiments'),
    _pm('fr_m005', 'PALAIS', 'Batiments'),
    _pm('fr_m006', 'TEMPLE', 'Batiments'),
    _pm('fr_m007', 'MUSEE', 'Batiments'),
    _pm('fr_m008', 'FUSEE', 'Espace'),
    _pm('fr_m009', 'PLANETE', 'Espace'),
    _pm('fr_m010', 'GALAXIE', 'Espace'),
    _pm('fr_m011', 'FOOTBALL', 'Sports'),
    _pm('fr_m012', 'TENNIS', 'Sports'),
    _pm('fr_m013', 'NATATION', 'Sports'),
    _pm('fr_m014', 'BOXE', 'Sports'),
    _pm('fr_m015', 'VOLLEY', 'Sports'),
    _pm('fr_m016', 'DIAMANT', 'Gemmes'),
    _pm('fr_m017', 'EMERAUDE', 'Gemmes'),
    _pm('fr_m018', 'SAPHIR', 'Gemmes'),
    _pm('fr_m019', 'RUBIS', 'Gemmes'),
    _pm('fr_m020', 'AUTOMNE', 'Saisons'),
    _pm('fr_m021', 'HIVER', 'Saisons'),
    _pm('fr_m022', 'PRINTEMPS', 'Saisons'),
    _pm('fr_m023', 'PAPILLON', 'Animaux'),
    _pm('fr_m024', 'PINGOUIN', 'Animaux'),
    _pm('fr_m025', 'GIRAFE', 'Animaux'),
    _pm('fr_m026', 'DAUPHIN', 'Animaux'),
    _pm('fr_m027', 'PERROQUET', 'Animaux'),
    _pm('fr_m028', 'FAUCON', 'Animaux'),
    _pm('fr_m029', 'ORDINATEUR', 'Technologie'),
    _pm('fr_m030', 'ROBOT', 'Technologie'),
    _pm('fr_m031', 'VOLCAN', 'Nature'),
    _pm('fr_m032', 'TREMBLEMENT', 'Nature'),
    _pm('fr_m033', 'ORAGE', 'Nature'),
    _pm('fr_m034', 'MEDECIN', 'Metiers'),
    _pm('fr_m035', 'PROFESSEUR', 'Metiers'),
    _pm('fr_m036', 'SOLDAT', 'Metiers'),
    _pm('fr_m037', 'CAPITAINE', 'Metiers'),
    _pm('fr_m038', 'OMBRE', 'Abstrait'),
    _pm('fr_m039', 'LIBERTE', 'Abstrait'),
    _pm('fr_m040', 'AVENTURE', 'Abstrait'),
    _pm('fr_m041', 'LEGENDE', 'Fantaisie'),
    _pm('fr_m042', 'BOUSSOLE', 'Aventure'),
    _pm('fr_m043', 'TRESOR', 'Aventure'),
    _pm('fr_m044', 'PHENIX', 'Mythologie'),
    _pm('fr_m045', 'LICORNE', 'Mythologie'),
    _pm('fr_m046', 'VIKING', 'Histoire'),
    _pm('fr_m047', 'GLADIATEUR', 'Histoire'),
    _pm('fr_m048', 'PIRATE', 'Aventure'),
    _pm('fr_m049', 'ANCRE', 'Navigation'),
    _pm('fr_m050', 'CRISTAL', 'Mineraux'),
    _pm('fr_m051', 'PANTHERE', 'Animaux'),
    _pm('fr_m052', 'ELEPHANT', 'Animaux'),
    _pm('fr_m053', 'CHOCOLAT', 'Nourriture'),
    _pm('fr_m054', 'POIVRE', 'Nourriture'),
    _pm('fr_m055', 'MARBRE', 'Materiaux'),
    _pm('fr_m056', 'VELOURS', 'Materiaux'),
    _pm('fr_m057', 'COURAGE', 'Abstrait'),
    _pm('fr_m058', 'HEROS', 'Abstrait'),
    _pm('fr_m059', 'CARTE', 'Aventure'),
    _pm('fr_m060', 'PHARAON', 'Histoire'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('fr_h001', 'FORET NOIRE', 'Nature'),
    _ph('fr_h002', 'ETOILE NORD', 'Astronomie'),
    _ph('fr_h003', 'CLAIR LUNE', 'Nature'),
    _ph('fr_h004', 'DRAGON FEU', 'Fantaisie'),
    _ph('fr_h005', 'CHATEAU GLACE', 'Fantaisie'),
    _ph('fr_h006', 'VENT TEMPETE', 'Meteo'),
    _ph('fr_h007', 'MINE OR', 'Extraction'),
    _ph('fr_h008', 'FOUDRE TONNERRE', 'Meteo'),
    _ph('fr_h009', 'LUNE ARGENT', 'Astronomie'),
    _ph('fr_h010', 'FEU SAUVAGE', 'Nature'),
    _ph('fr_h011', 'TEMPETE SABLE', 'Meteo'),
    _ph('fr_h012', 'MER PROFONDE', 'Nature'),
    _ph('fr_h013', 'POUSSIERE ETOILE', 'Espace'),
    _ph('fr_h014', 'MEUTE LOUPS', 'Animaux'),
    _ph('fr_h015', 'VAISSEAU FANTOME', 'Mythologie'),
    _ph('fr_h016', 'TOUR SOMBRE', 'Fantaisie'),
    _ph('fr_h017', 'RECIF CORAIL', 'Nature'),
    _ph('fr_h018', 'FLOCON NEIGE', 'Nature'),
    _ph('fr_h019', 'PIERRE LUNE', 'Gemmes'),
    _ph('fr_h020', 'EPEE FLAMMES', 'Fantaisie'),
    _ph('fr_h021', 'GRANDE MURAILLE', 'Monuments'),
    _ph('fr_h022', 'ARC CIEL', 'Nature'),
    _ph('fr_h023', 'GROTTE CRISTAL', 'Nature'),
    _ph('fr_h024', 'PONT PIERRE', 'Constructions'),
    _ph('fr_h025', 'FORET SOMBRE', 'Nature'),
    _ph('fr_h026', 'OISEAU FEU', 'Mythologie'),
    _ph('fr_h027', 'OURS POLAIRE', 'Animaux'),
    _ph('fr_h028', 'FAUCON NUIT', 'Animaux'),
    _ph('fr_h029', 'DRAGON ROUGE', 'Fantaisie'),
    _ph('fr_h030', 'TROU NOIR', 'Espace'),
    _ph('fr_h031', 'VENT SOLAIRE', 'Espace'),
    _ph('fr_h032', 'CASCADE EAU', 'Nature'),
    _ph('fr_h033', 'SOMMET MONTAGNE', 'Nature'),
    _ph('fr_h034', 'ILE PERDUE', 'Aventure'),
    _ph('fr_h035', 'COFFRE TRESOR', 'Aventure'),
    _ph('fr_h036', 'AUBE DOREE', 'Nature'),
    _ph('fr_h037', 'NUIT ETOILEE', 'Nature'),
    _ph('fr_h038', 'BAGUETTE MAGIQUE', 'Fantaisie'),
    _ph('fr_h039', 'CAVALIER DRAGON', 'Fantaisie'),
    _ph('fr_h040', 'MOULIN VENT', 'Constructions'),
    _ph('fr_h041', 'PHARE LUMIERE', 'Constructions'),
    _ph('fr_h042', 'MER BRUME', 'Nature'),
    _ph('fr_h043', 'VAGUE TEMPETE', 'Nature'),
    _ph('fr_h044', 'FEUX ARTIFICE', 'Fetes'),
    _ph('fr_h045', 'GEL ETERNEL', 'Nature'),
    _ph('fr_h046', 'SABLE TEMPS', 'Abstrait'),
    _ph('fr_h047', 'CIEL ETOILE', 'Nature'),
    _ph('fr_h048', 'ROSE VENTS', 'Navigation'),
    _ph('fr_h049', 'LOUP BLANC', 'Animaux'),
    _ph('fr_h050', 'CHASSEUR NUIT', 'Fantaisie'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'fr',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'fr',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'fr',
      );
}
