import '../../data/models/puzzle_model.dart';

/// Turkish puzzle database — Popular video games across all difficulties.
class PuzzlesTr {
  PuzzlesTr._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('tr_e001', 'MARIO', 'Nintendo'),
    _p('tr_e002', 'ZELDA', 'Nintendo'),
    _p('tr_e003', 'SONIC', 'Sega'),
    _p('tr_e004', 'TETRIS', 'Bulmaca'),
    _p('tr_e005', 'HADES', 'Roguelike'),
    _p('tr_e006', 'LIMBO', 'Bagimsiz'),
    _p('tr_e007', 'DOOM', 'FPS'),
    _p('tr_e008', 'DOTA', 'MOBA'),
    _p('tr_e009', 'HALO', 'FPS'),
    _p('tr_e010', 'PUBG', 'Battle Royale'),
    _p('tr_e011', 'FABLE', 'RPG'),
    _p('tr_e012', 'STRAY', 'Macera'),
    _p('tr_e013', 'SIFU', 'Dovus'),
    _p('tr_e014', 'TUNIC', 'Macera'),
    _p('tr_e015', 'KIRBY', 'Nintendo'),
    _p('tr_e016', 'SPORE', 'Simulasyon'),
    _p('tr_e017', 'CRYSIS', 'FPS'),
    _p('tr_e018', 'RUST', 'Hayatta Kalma'),
    _p('tr_e019', 'PREY', 'FPS'),
    _p('tr_e020', 'SOMA', 'Korku'),
    _p('tr_e021', 'ABZU', 'Macera'),
    _p('tr_e022', 'MYST', 'Bulmaca'),
    _p('tr_e023', 'GRIS', 'Bagimsiz'),
    _p('tr_e024', 'OKAMI', 'Aksiyon'),
    _p('tr_e025', 'PYRE', 'RPG'),
    _p('tr_e026', 'BRAID', 'Bagimsiz'),
    _p('tr_e027', 'SCORN', 'Korku'),
    _p('tr_e028', 'FURI', 'Aksiyon'),
    _p('tr_e029', 'KENA', 'Aksiyon'),
    _p('tr_e030', 'EMBER', 'RPG'),
    _p('tr_e031', 'TRINE', 'Bulmaca'),
    _p('tr_e032', 'OMORI', 'RPG'),
    _p('tr_e033', 'ATLAS', 'Hayatta Kalma'),
    _p('tr_e034', 'NEON', 'Aksiyon'),
    _p('tr_e035', 'HAVEN', 'RPG'),
    _p('tr_e036', 'DISCO', 'RPG'),
    _p('tr_e037', 'NORCO', 'Macera'),
    _p('tr_e038', 'TOEM', 'Bulmaca'),
    _p('tr_e039', 'SABLE', 'Macera'),
    _p('tr_e040', 'ANNO', 'Strateji'),
    _p('tr_e041', 'WORMS', 'Strateji'),
    _p('tr_e042', 'RISK', 'Strateji'),
    _p('tr_e043', 'LEGO', 'Macera'),
    _p('tr_e044', 'SIMS', 'Simulasyon'),
    _p('tr_e045', 'OLIJA', 'Aksiyon'),
    _p('tr_e046', 'YOKU', 'Platform'),
    _p('tr_e047', 'FEIST', 'Bagimsiz'),
    _p('tr_e048', 'EDITH', 'Macera'),
    _p('tr_e049', 'FLOW', 'Bagimsiz'),
    _p('tr_e050', 'RAGE', 'FPS'),
    _p('tr_e051', 'STEEP', 'Spor'),
    _p('tr_e052', 'VIGOR', 'Hayatta Kalma'),
    _p('tr_e053', 'BULLY', 'Aksiyon'),
    _p('tr_e054', 'ARMA', 'Simulasyon'),
    _p('tr_e055', 'RYSE', 'Aksiyon'),
    _p('tr_e056', 'RUINER', 'Aksiyon'),
    _p('tr_e057', 'INSIDE', 'Bagimsiz'),
    _p('tr_e058', 'CUPHEAD', 'Platform'),
    _p('tr_e059', 'CELESTE', 'Platform'),
    _p('tr_e060', 'VALHEIM', 'Hayatta Kalma'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('tr_m001', 'SKYRIM', 'RPG'),
    _pm('tr_m002', 'PORTAL', 'Bulmaca'),
    _pm('tr_m003', 'HITMAN', 'Gizlilik'),
    _pm('tr_m004', 'DIABLO', 'RPG'),
    _pm('tr_m005', 'FALLOUT', 'RPG'),
    _pm('tr_m006', 'DESTINY', 'FPS'),
    _pm('tr_m007', 'FORTNITE', 'Battle Royale'),
    _pm('tr_m008', 'OVERWATCH', 'FPS'),
    _pm('tr_m009', 'MINECRAFT', 'Sandbox'),
    _pm('tr_m010', 'TERRARIA', 'Sandbox'),
    _pm('tr_m011', 'OUTLAST', 'Korku'),
    _pm('tr_m012', 'CONTROL', 'Aksiyon'),
    _pm('tr_m013', 'BAYONETTA', 'Aksiyon'),
    _pm('tr_m014', 'BLOODBORNE', 'RPG'),
    _pm('tr_m015', 'SEKIRO', 'Aksiyon'),
    _pm('tr_m016', 'RETURNAL', 'Roguelike'),
    _pm('tr_m017', 'TEKKEN', 'Dovus'),
    _pm('tr_m018', 'UNCHARTED', 'Macera'),
    _pm('tr_m019', 'HORIZON', 'RPG'),
    _pm('tr_m020', 'TITANFALL', 'FPS'),
    _pm('tr_m021', 'WITCHER', 'RPG'),
    _pm('tr_m022', 'CYBERPUNK', 'RPG'),
    _pm('tr_m023', 'SUBNAUTICA', 'Hayatta Kalma'),
    _pm('tr_m024', 'DISHONORED', 'Gizlilik'),
    _pm('tr_m025', 'METROID', 'Macera'),
    _pm('tr_m026', 'RAYMAN', 'Platform'),
    _pm('tr_m027', 'RATCHET', 'Platform'),
    _pm('tr_m028', 'HELLBLADE', 'Aksiyon'),
    _pm('tr_m029', 'JOURNEY', 'Bagimsiz'),
    _pm('tr_m030', 'FIREWATCH', 'Macera'),
    _pm('tr_m031', 'UNDERTALE', 'RPG'),
    _pm('tr_m032', 'FACTORIO', 'Simulasyon'),
    _pm('tr_m033', 'RIMWORLD', 'Simulasyon'),
    _pm('tr_m034', 'SPLATOON', 'Nisnanci'),
    _pm('tr_m035', 'XENOBLADE', 'RPG'),
    _pm('tr_m036', 'STARFIELD', 'RPG'),
    _pm('tr_m037', 'REMNANT', 'Aksiyon'),
    _pm('tr_m038', 'BIOSHOCK', 'FPS'),
    _pm('tr_m039', 'WARCRAFT', 'Strateji'),
    _pm('tr_m040', 'STARCRAFT', 'Strateji'),
    _pm('tr_m041', 'DEATHLOOP', 'FPS'),
    _pm('tr_m042', 'INFAMOUS', 'Aksiyon'),
    _pm('tr_m043', 'VAMPYR', 'RPG'),
    _pm('tr_m044', 'NIOH', 'Aksiyon'),
    _pm('tr_m045', 'TROPICO', 'Simulasyon'),
    _pm('tr_m046', 'TEMTEM', 'RPG'),
    _pm('tr_m047', 'DARKEST', 'RPG'),
    _pm('tr_m048', 'HOLLOW', 'Platform'),
    _pm('tr_m049', 'BASTION', 'RPG'),
    _pm('tr_m050', 'SPELUNKY', 'Roguelike'),
    _pm('tr_m051', 'ASTRONEER', 'Hayatta Kalma'),
    _pm('tr_m052', 'CHIVALRY', 'Aksiyon'),
    _pm('tr_m053', 'GREEDFALL', 'RPG'),
    _pm('tr_m054', 'KENSHI', 'RPG'),
    _pm('tr_m055', 'ARAGAMI', 'Gizlilik'),
    _pm('tr_m056', 'BIOMUTANT', 'RPG'),
    _pm('tr_m057', 'GHOSTWIRE', 'Aksiyon'),
    _pm('tr_m058', 'INSCRYPTION', 'Kart Oyunu'),
    _pm('tr_m059', 'OUTRIDERS', 'Nisnanci'),
    _pm('tr_m060', 'MONSTER', 'RPG'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('tr_h001', 'ELDEN RING', 'RPG'),
    _ph('tr_h002', 'SAVAS TANRISI', 'Aksiyon'),
    _ph('tr_h003', 'KARANLIK RUHLAR', 'RPG'),
    _ph('tr_h004', 'KIZIL OLUM', 'Acik Dunya'),
    _ph('tr_h005', 'SON HAYATTA', 'Macera'),
    _ph('tr_h006', 'FINAL FANTEZI', 'RPG'),
    _ph('tr_h007', 'KUTLE ETKISI', 'RPG'),
    _ph('tr_h008', 'OLU UZAY', 'Korku'),
    _ph('tr_h009', 'MEZAR AVCISI', 'Macera'),
    _ph('tr_h010', 'METAL DISLI', 'Gizlilik'),
    _ph('tr_h011', 'YARIM HAYAT', 'FPS'),
    _ph('tr_h012', 'OLUM SARMALASI', 'Macera'),
    _ph('tr_h013', 'HAYALET KESIF', 'Nisnanci'),
    _ph('tr_h014', 'EJDER CAGI', 'RPG'),
    _ph('tr_h015', 'SUPER DOVUS', 'Dovus'),
    _ph('tr_h016', 'HAYVAN GECISI', 'Simulasyon'),
    _ph('tr_h017', 'SOKAK DOVUSU', 'Dovus'),
    _ph('tr_h018', 'DISLI SAVAS', 'Nisnanci'),
    _ph('tr_h019', 'ROKET LIGI', 'Spor'),
    _ph('tr_h020', 'PRENS PERS', 'Aksiyon'),
    _ph('tr_h021', 'BEKCI KOPEKLER', 'Acik Dunya'),
    _ph('tr_h022', 'OLEN ISIK', 'Korku'),
    _ph('tr_h023', 'ORUMCEK ADAM', 'Aksiyon'),
    _ph('tr_h024', 'YILDIZ SAVASLARI', 'Aksiyon'),
    _ph('tr_h025', 'GOREV CAGRISI', 'FPS'),
    _ph('tr_h026', 'LIG EFSANELER', 'MOBA'),
    _ph('tr_h027', 'BALDURS KAPISI', 'RPG'),
    _ph('tr_h028', 'UZAK CIGLIK', 'FPS'),
    _ph('tr_h029', 'HIZ TUTKUSU', 'Yaris'),
    _ph('tr_h030', 'SEHIR GOKDELENI', 'Simulasyon'),
    _ph('tr_h031', 'SEYTAN AGLAR', 'Aksiyon'),
    _ph('tr_h032', 'GOLGE DEVLER', 'Macera'),
    _ph('tr_h033', 'TOPLAM SAVAS', 'Strateji'),
    _ph('tr_h034', 'HIRSIZ DENIZI', 'Macera'),
    _ph('tr_h035', 'TEPE EFSANELERI', 'Battle Royale'),
    _ph('tr_h036', 'IMPARATORLUK CAGI', 'Strateji'),
    _ph('tr_h037', 'DEMIR HASAT', 'Strateji'),
    _ph('tr_h038', 'HAKLI SEBEP', 'Aksiyon'),
    _ph('tr_h039', 'KAYIP GEMI', 'MMORPG'),
    _ph('tr_h040', 'YABANI KALPLER', 'Aksiyon'),
    _ph('tr_h041', 'GECMIS GUNLER', 'Aksiyon'),
    _ph('tr_h042', 'SOL OLUM', 'FPS'),
    _ph('tr_h043', 'OLU ADA', 'Hayatta Kalma'),
    _ph('tr_h044', 'DUSEN ADAMLAR', 'Parti'),
    _ph('tr_h045', 'DERIN KAYA', 'Coop'),
    _ph('tr_h046', 'KOTULUK ICINDE', 'Korku'),
    _ph('tr_h047', 'LEGO YILDIZ', 'Macera'),
    _ph('tr_h048', 'GOLGE MORDOR', 'Aksiyon'),
    _ph('tr_h049', 'EBEDI KIYANET', 'FPS'),
    _ph('tr_h050', 'DIS CEVRE', 'Macera'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'tr',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'tr',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'tr',
      );
}
