import '../../data/models/puzzle_model.dart';

/// Spanish puzzle database — 170+ puzzles across all difficulties.
class PuzzlesEs {
  PuzzlesEs._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('es_e001', 'MANZANA', 'Frutas'),
    _p('es_e002', 'PERA', 'Frutas'),
    _p('es_e003', 'LIMON', 'Frutas'),
    _p('es_e004', 'NARANJA', 'Frutas'),
    _p('es_e005', 'PLATANO', 'Frutas'),
    _p('es_e006', 'CEREZA', 'Frutas'),
    _p('es_e007', 'MELON', 'Frutas'),
    _p('es_e008', 'CIRUELA', 'Frutas'),
    _p('es_e009', 'FRESA', 'Frutas'),
    _p('es_e010', 'DURAZNO', 'Frutas'),
    _p('es_e011', 'GATO', 'Animales'),
    _p('es_e012', 'PERRO', 'Animales'),
    _p('es_e013', 'CABALLO', 'Animales'),
    _p('es_e014', 'LEON', 'Animales'),
    _p('es_e015', 'TIGRE', 'Animales'),
    _p('es_e016', 'AGUILA', 'Animales'),
    _p('es_e017', 'SERPIENTE', 'Animales'),
    _p('es_e018', 'RATON', 'Animales'),
    _p('es_e019', 'ZORRO', 'Animales'),
    _p('es_e020', 'OSO', 'Animales'),
    _p('es_e021', 'SILLA', 'Muebles'),
    _p('es_e022', 'MESA', 'Muebles'),
    _p('es_e023', 'CAMA', 'Muebles'),
    _p('es_e024', 'SOFA', 'Muebles'),
    _p('es_e025', 'ESPEJO', 'Muebles'),
    _p('es_e026', 'PAN', 'Comida'),
    _p('es_e027', 'QUESO', 'Comida'),
    _p('es_e028', 'SOPA', 'Comida'),
    _p('es_e029', 'ARROZ', 'Comida'),
    _p('es_e030', 'ENSALADA', 'Comida'),
    _p('es_e031', 'NUBE', 'Naturaleza'),
    _p('es_e032', 'ESTRELLA', 'Naturaleza'),
    _p('es_e033', 'RIO', 'Naturaleza'),
    _p('es_e034', 'MONTE', 'Naturaleza'),
    _p('es_e035', 'BOSQUE', 'Naturaleza'),
    _p('es_e036', 'OCEANO', 'Naturaleza'),
    _p('es_e037', 'LLAMA', 'Naturaleza'),
    _p('es_e038', 'PIEDRA', 'Naturaleza'),
    _p('es_e039', 'VIENTO', 'Naturaleza'),
    _p('es_e040', 'LLUVIA', 'Naturaleza'),
    _p('es_e041', 'LIBRO', 'Objetos'),
    _p('es_e042', 'PLUMA', 'Objetos'),
    _p('es_e043', 'CORONA', 'Objetos'),
    _p('es_e044', 'ESPADA', 'Objetos'),
    _p('es_e045', 'ESCUDO', 'Objetos'),
    _p('es_e046', 'ESCUELA', 'Lugares'),
    _p('es_e047', 'PLAYA', 'Lugares'),
    _p('es_e048', 'TORRE', 'Lugares'),
    _p('es_e049', 'JARDIN', 'Lugares'),
    _p('es_e050', 'PLAZA', 'Lugares'),
    _p('es_e051', 'PLATA', 'Metales'),
    _p('es_e052', 'COBRE', 'Metales'),
    _p('es_e053', 'HIERRO', 'Metales'),
    _p('es_e054', 'SEDA', 'Telas'),
    _p('es_e055', 'ALGODON', 'Telas'),
    _p('es_e056', 'PIANO', 'Musica'),
    _p('es_e057', 'VIOLIN', 'Musica'),
    _p('es_e058', 'FLAUTA', 'Musica'),
    _p('es_e059', 'GUITARRA', 'Musica'),
    _p('es_e060', 'SUENO', 'Abstracto'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('es_m001', 'CABALLERO', 'Fantasia'),
    _pm('es_m002', 'DRAGON', 'Fantasia'),
    _pm('es_m003', 'HECHICERO', 'Fantasia'),
    _pm('es_m004', 'CASTILLO', 'Edificios'),
    _pm('es_m005', 'PALACIO', 'Edificios'),
    _pm('es_m006', 'TEMPLO', 'Edificios'),
    _pm('es_m007', 'MUSEO', 'Edificios'),
    _pm('es_m008', 'COHETE', 'Espacio'),
    _pm('es_m009', 'PLANETA', 'Espacio'),
    _pm('es_m010', 'GALAXIA', 'Espacio'),
    _pm('es_m011', 'FUTBOL', 'Deportes'),
    _pm('es_m012', 'TENIS', 'Deportes'),
    _pm('es_m013', 'NATACION', 'Deportes'),
    _pm('es_m014', 'BOXEO', 'Deportes'),
    _pm('es_m015', 'VOLEIBOL', 'Deportes'),
    _pm('es_m016', 'DIAMANTE', 'Gemas'),
    _pm('es_m017', 'ESMERALDA', 'Gemas'),
    _pm('es_m018', 'ZAFIRO', 'Gemas'),
    _pm('es_m019', 'RUBI', 'Gemas'),
    _pm('es_m020', 'OTONO', 'Estaciones'),
    _pm('es_m021', 'INVIERNO', 'Estaciones'),
    _pm('es_m022', 'VERANO', 'Estaciones'),
    _pm('es_m023', 'MARIPOSA', 'Animales'),
    _pm('es_m024', 'PINGUINO', 'Animales'),
    _pm('es_m025', 'JIRAFA', 'Animales'),
    _pm('es_m026', 'DELFIN', 'Animales'),
    _pm('es_m027', 'LORO', 'Animales'),
    _pm('es_m028', 'HALCON', 'Animales'),
    _pm('es_m029', 'COMPUTADORA', 'Tecnologia'),
    _pm('es_m030', 'ROBOT', 'Tecnologia'),
    _pm('es_m031', 'VOLCAN', 'Naturaleza'),
    _pm('es_m032', 'TERREMOTO', 'Naturaleza'),
    _pm('es_m033', 'TORMENTA', 'Naturaleza'),
    _pm('es_m034', 'MEDICO', 'Profesiones'),
    _pm('es_m035', 'PROFESOR', 'Profesiones'),
    _pm('es_m036', 'SOLDADO', 'Profesiones'),
    _pm('es_m037', 'CAPITAN', 'Profesiones'),
    _pm('es_m038', 'SOMBRA', 'Abstracto'),
    _pm('es_m039', 'LIBERTAD', 'Abstracto'),
    _pm('es_m040', 'AVENTURA', 'Abstracto'),
    _pm('es_m041', 'LEYENDA', 'Fantasia'),
    _pm('es_m042', 'BRUJULA', 'Aventura'),
    _pm('es_m043', 'TESORO', 'Aventura'),
    _pm('es_m044', 'FENIX', 'Mitologia'),
    _pm('es_m045', 'UNICORNIO', 'Mitologia'),
    _pm('es_m046', 'VIKINGO', 'Historia'),
    _pm('es_m047', 'GLADIADOR', 'Historia'),
    _pm('es_m048', 'PIRATA', 'Aventura'),
    _pm('es_m049', 'ANCLA', 'Navegacion'),
    _pm('es_m050', 'CRISTAL', 'Minerales'),
    _pm('es_m051', 'PANTERA', 'Animales'),
    _pm('es_m052', 'ELEFANTE', 'Animales'),
    _pm('es_m053', 'CHOCOLATE', 'Comida'),
    _pm('es_m054', 'PIMIENTA', 'Comida'),
    _pm('es_m055', 'MARMOL', 'Materiales'),
    _pm('es_m056', 'TERCIOPELO', 'Materiales'),
    _pm('es_m057', 'CORAJE', 'Abstracto'),
    _pm('es_m058', 'HEROE', 'Abstracto'),
    _pm('es_m059', 'MAPA', 'Aventura'),
    _pm('es_m060', 'FARAON', 'Historia'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('es_h001', 'BOSQUE NEGRO', 'Naturaleza'),
    _ph('es_h002', 'ESTRELLA POLAR', 'Astronomia'),
    _ph('es_h003', 'CLARO LUNA', 'Naturaleza'),
    _ph('es_h004', 'DRAGON FUEGO', 'Fantasia'),
    _ph('es_h005', 'CASTILLO HIELO', 'Fantasia'),
    _ph('es_h006', 'VIENTO TORMENTA', 'Clima'),
    _ph('es_h007', 'MINA ORO', 'Mineria'),
    _ph('es_h008', 'RAYO TRUENO', 'Clima'),
    _ph('es_h009', 'LUNA PLATA', 'Astronomia'),
    _ph('es_h010', 'FUEGO SALVAJE', 'Naturaleza'),
    _ph('es_h011', 'TORMENTA ARENA', 'Clima'),
    _ph('es_h012', 'MAR PROFUNDO', 'Naturaleza'),
    _ph('es_h013', 'POLVO ESTRELLAS', 'Espacio'),
    _ph('es_h014', 'MANADA LOBOS', 'Animales'),
    _ph('es_h015', 'BARCO FANTASMA', 'Mitologia'),
    _ph('es_h016', 'TORRE OSCURA', 'Fantasia'),
    _ph('es_h017', 'ARRECIFE CORAL', 'Naturaleza'),
    _ph('es_h018', 'COPO NIEVE', 'Naturaleza'),
    _ph('es_h019', 'PIEDRA LUNA', 'Gemas'),
    _ph('es_h020', 'ESPADA LLAMAS', 'Fantasia'),
    _ph('es_h021', 'GRAN MURALLA', 'Monumentos'),
    _ph('es_h022', 'ARCO IRIS', 'Naturaleza'),
    _ph('es_h023', 'CUEVA CRISTAL', 'Naturaleza'),
    _ph('es_h024', 'PUENTE PIEDRA', 'Construcciones'),
    _ph('es_h025', 'SELVA OSCURA', 'Naturaleza'),
    _ph('es_h026', 'PAJARO FUEGO', 'Mitologia'),
    _ph('es_h027', 'OSO POLAR', 'Animales'),
    _ph('es_h028', 'HALCON NOCHE', 'Animales'),
    _ph('es_h029', 'DRAGON ROJO', 'Fantasia'),
    _ph('es_h030', 'AGUJERO NEGRO', 'Espacio'),
    _ph('es_h031', 'VIENTO SOLAR', 'Espacio'),
    _ph('es_h032', 'CASCADA AGUA', 'Naturaleza'),
    _ph('es_h033', 'CIMA MONTANA', 'Naturaleza'),
    _ph('es_h034', 'ISLA PERDIDA', 'Aventura'),
    _ph('es_h035', 'COFRE TESORO', 'Aventura'),
    _ph('es_h036', 'ALBA DORADA', 'Naturaleza'),
    _ph('es_h037', 'NOCHE ESTRELLADA', 'Naturaleza'),
    _ph('es_h038', 'VARITA MAGICA', 'Fantasia'),
    _ph('es_h039', 'JINETE DRAGON', 'Fantasia'),
    _ph('es_h040', 'MOLINO VIENTO', 'Construcciones'),
    _ph('es_h041', 'FARO LUZ', 'Construcciones'),
    _ph('es_h042', 'MAR NIEBLA', 'Naturaleza'),
    _ph('es_h043', 'OLA TORMENTA', 'Naturaleza'),
    _ph('es_h044', 'FUEGOS ARTIFICIALES', 'Fiestas'),
    _ph('es_h045', 'HIELO ETERNO', 'Naturaleza'),
    _ph('es_h046', 'ARENA TIEMPO', 'Abstracto'),
    _ph('es_h047', 'CIELO ESTRELLADO', 'Naturaleza'),
    _ph('es_h048', 'ROSA VIENTOS', 'Navegacion'),
    _ph('es_h049', 'LOBO BLANCO', 'Animales'),
    _ph('es_h050', 'CAZADOR NOCHE', 'Fantasia'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'es',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'es',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'es',
      );
}
