import '../../data/models/puzzle_model.dart';

/// German puzzle database — Popular video games across all difficulties.
class PuzzlesDe {
  PuzzlesDe._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('de_e001', 'MARIO', 'Nintendo'),
    _p('de_e002', 'ZELDA', 'Nintendo'),
    _p('de_e003', 'SONIC', 'Sega'),
    _p('de_e004', 'TETRIS', 'Raetsel'),
    _p('de_e005', 'HADES', 'Roguelike'),
    _p('de_e006', 'LIMBO', 'Indie'),
    _p('de_e007', 'DOOM', 'Shooter'),
    _p('de_e008', 'DOTA', 'MOBA'),
    _p('de_e009', 'HALO', 'Shooter'),
    _p('de_e010', 'PUBG', 'Battle Royale'),
    _p('de_e011', 'FABLE', 'Rollenspiel'),
    _p('de_e012', 'STRAY', 'Abenteuer'),
    _p('de_e013', 'SIFU', 'Kampf'),
    _p('de_e014', 'TUNIC', 'Abenteuer'),
    _p('de_e015', 'KIRBY', 'Nintendo'),
    _p('de_e016', 'SPORE', 'Simulation'),
    _p('de_e017', 'CRYSIS', 'Shooter'),
    _p('de_e018', 'RUST', 'Ueberleben'),
    _p('de_e019', 'PREY', 'Shooter'),
    _p('de_e020', 'SOMA', 'Horror'),
    _p('de_e021', 'ABZU', 'Abenteuer'),
    _p('de_e022', 'MYST', 'Raetsel'),
    _p('de_e023', 'GRIS', 'Indie'),
    _p('de_e024', 'OKAMI', 'Aktion'),
    _p('de_e025', 'PYRE', 'Rollenspiel'),
    _p('de_e026', 'BRAID', 'Indie'),
    _p('de_e027', 'SCORN', 'Horror'),
    _p('de_e028', 'FURI', 'Aktion'),
    _p('de_e029', 'KENA', 'Aktion'),
    _p('de_e030', 'EMBER', 'Rollenspiel'),
    _p('de_e031', 'TRINE', 'Raetsel'),
    _p('de_e032', 'OMORI', 'Rollenspiel'),
    _p('de_e033', 'ATLAS', 'Ueberleben'),
    _p('de_e034', 'NEON', 'Aktion'),
    _p('de_e035', 'HAVEN', 'Rollenspiel'),
    _p('de_e036', 'DISCO', 'Rollenspiel'),
    _p('de_e037', 'NORCO', 'Abenteuer'),
    _p('de_e038', 'TOEM', 'Raetsel'),
    _p('de_e039', 'SABLE', 'Abenteuer'),
    _p('de_e040', 'ANNO', 'Strategie'),
    _p('de_e041', 'WORMS', 'Strategie'),
    _p('de_e042', 'RISK', 'Strategie'),
    _p('de_e043', 'LEGO', 'Abenteuer'),
    _p('de_e044', 'SIMS', 'Simulation'),
    _p('de_e045', 'OLIJA', 'Aktion'),
    _p('de_e046', 'YOKU', 'Plattform'),
    _p('de_e047', 'FEIST', 'Indie'),
    _p('de_e048', 'EDITH', 'Abenteuer'),
    _p('de_e049', 'FLOW', 'Indie'),
    _p('de_e050', 'RAGE', 'Shooter'),
    _p('de_e051', 'STEEP', 'Sport'),
    _p('de_e052', 'VIGOR', 'Ueberleben'),
    _p('de_e053', 'BULLY', 'Aktion'),
    _p('de_e054', 'ARMA', 'Simulation'),
    _p('de_e055', 'RYSE', 'Aktion'),
    _p('de_e056', 'RUINER', 'Aktion'),
    _p('de_e057', 'INSIDE', 'Indie'),
    _p('de_e058', 'CUPHEAD', 'Plattform'),
    _p('de_e059', 'CELESTE', 'Plattform'),
    _p('de_e060', 'VALHEIM', 'Ueberleben'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('de_m001', 'SKYRIM', 'Rollenspiel'),
    _pm('de_m002', 'PORTAL', 'Raetsel'),
    _pm('de_m003', 'HITMAN', 'Schleich'),
    _pm('de_m004', 'DIABLO', 'Rollenspiel'),
    _pm('de_m005', 'FALLOUT', 'Rollenspiel'),
    _pm('de_m006', 'DESTINY', 'Shooter'),
    _pm('de_m007', 'FORTNITE', 'Battle Royale'),
    _pm('de_m008', 'OVERWATCH', 'Shooter'),
    _pm('de_m009', 'MINECRAFT', 'Sandbox'),
    _pm('de_m010', 'TERRARIA', 'Sandbox'),
    _pm('de_m011', 'OUTLAST', 'Horror'),
    _pm('de_m012', 'CONTROL', 'Aktion'),
    _pm('de_m013', 'BAYONETTA', 'Aktion'),
    _pm('de_m014', 'BLOODBORNE', 'Rollenspiel'),
    _pm('de_m015', 'SEKIRO', 'Aktion'),
    _pm('de_m016', 'RETURNAL', 'Roguelike'),
    _pm('de_m017', 'TEKKEN', 'Kampf'),
    _pm('de_m018', 'UNCHARTED', 'Abenteuer'),
    _pm('de_m019', 'HORIZON', 'Rollenspiel'),
    _pm('de_m020', 'TITANFALL', 'Shooter'),
    _pm('de_m021', 'WITCHER', 'Rollenspiel'),
    _pm('de_m022', 'CYBERPUNK', 'Rollenspiel'),
    _pm('de_m023', 'SUBNAUTICA', 'Ueberleben'),
    _pm('de_m024', 'DISHONORED', 'Schleich'),
    _pm('de_m025', 'METROID', 'Abenteuer'),
    _pm('de_m026', 'RAYMAN', 'Plattform'),
    _pm('de_m027', 'RATCHET', 'Plattform'),
    _pm('de_m028', 'HELLBLADE', 'Aktion'),
    _pm('de_m029', 'JOURNEY', 'Indie'),
    _pm('de_m030', 'FIREWATCH', 'Abenteuer'),
    _pm('de_m031', 'UNDERTALE', 'Rollenspiel'),
    _pm('de_m032', 'FACTORIO', 'Simulation'),
    _pm('de_m033', 'RIMWORLD', 'Simulation'),
    _pm('de_m034', 'SPLATOON', 'Shooter'),
    _pm('de_m035', 'XENOBLADE', 'Rollenspiel'),
    _pm('de_m036', 'STARFIELD', 'Rollenspiel'),
    _pm('de_m037', 'REMNANT', 'Aktion'),
    _pm('de_m038', 'BIOSHOCK', 'Shooter'),
    _pm('de_m039', 'WARCRAFT', 'Strategie'),
    _pm('de_m040', 'STARCRAFT', 'Strategie'),
    _pm('de_m041', 'DEATHLOOP', 'Shooter'),
    _pm('de_m042', 'INFAMOUS', 'Aktion'),
    _pm('de_m043', 'VAMPYR', 'Rollenspiel'),
    _pm('de_m044', 'NIOH', 'Aktion'),
    _pm('de_m045', 'TROPICO', 'Simulation'),
    _pm('de_m046', 'TEMTEM', 'Rollenspiel'),
    _pm('de_m047', 'DARKEST', 'Rollenspiel'),
    _pm('de_m048', 'HOLLOW', 'Plattform'),
    _pm('de_m049', 'BASTION', 'Rollenspiel'),
    _pm('de_m050', 'SPELUNKY', 'Roguelike'),
    _pm('de_m051', 'ASTRONEER', 'Ueberleben'),
    _pm('de_m052', 'CHIVALRY', 'Aktion'),
    _pm('de_m053', 'GREEDFALL', 'Rollenspiel'),
    _pm('de_m054', 'KENSHI', 'Rollenspiel'),
    _pm('de_m055', 'ARAGAMI', 'Schleich'),
    _pm('de_m056', 'BIOMUTANT', 'Rollenspiel'),
    _pm('de_m057', 'GHOSTWIRE', 'Aktion'),
    _pm('de_m058', 'INSCRYPTION', 'Kartenspiel'),
    _pm('de_m059', 'OUTRIDERS', 'Shooter'),
    _pm('de_m060', 'MONSTER', 'Rollenspiel'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('de_h001', 'ELDEN RING', 'Rollenspiel'),
    _ph('de_h002', 'GOTT KRIEG', 'Aktion'),
    _ph('de_h003', 'DUNKLE SEELEN', 'Rollenspiel'),
    _ph('de_h004', 'ROTE ERLOESUNG', 'Offene Welt'),
    _ph('de_h005', 'LETZTE VON UNS', 'Abenteuer'),
    _ph('de_h006', 'FINAL FANTASY', 'Rollenspiel'),
    _ph('de_h007', 'MASSE EFFEKT', 'Rollenspiel'),
    _ph('de_h008', 'TOTER RAUM', 'Horror'),
    _ph('de_h009', 'GRAB RAEUBER', 'Abenteuer'),
    _ph('de_h010', 'METALL GETRIEBE', 'Schleich'),
    _ph('de_h011', 'HALBES LEBEN', 'Shooter'),
    _ph('de_h012', 'TODES STRANG', 'Abenteuer'),
    _ph('de_h013', 'GEIST AUFKLAERER', 'Shooter'),
    _ph('de_h014', 'DRACHEN ALTER', 'Rollenspiel'),
    _ph('de_h015', 'SUPER KAMPF', 'Kampf'),
    _ph('de_h016', 'TIER KREUZUNG', 'Simulation'),
    _ph('de_h017', 'STRASSEN KAMPF', 'Kampf'),
    _ph('de_h018', 'ZAHNRAD KRIEG', 'Shooter'),
    _ph('de_h019', 'RAKETEN LIGA', 'Sport'),
    _ph('de_h020', 'PRINZ PERSIEN', 'Aktion'),
    _ph('de_h021', 'WACH HUNDE', 'Offene Welt'),
    _ph('de_h022', 'STERBENDES LICHT', 'Horror'),
    _ph('de_h023', 'SPINNEN MANN', 'Aktion'),
    _ph('de_h024', 'STERN KRIEGE', 'Aktion'),
    _ph('de_h025', 'RUF DER PFLICHT', 'Shooter'),
    _ph('de_h026', 'LIGA LEGENDEN', 'MOBA'),
    _ph('de_h027', 'BALDURS TOR', 'Rollenspiel'),
    _ph('de_h028', 'FERN SCHREI', 'Shooter'),
    _ph('de_h029', 'BRAUCHE TEMPO', 'Rennspiel'),
    _ph('de_h030', 'STADT HORIZONT', 'Simulation'),
    _ph('de_h031', 'TEUFEL WEINEN', 'Aktion'),
    _ph('de_h032', 'SCHATTEN KOLOSS', 'Abenteuer'),
    _ph('de_h033', 'GESAMT KRIEG', 'Strategie'),
    _ph('de_h034', 'MEER DIEBE', 'Abenteuer'),
    _ph('de_h035', 'GIPFEL LEGENDEN', 'Battle Royale'),
    _ph('de_h036', 'ALTER REICHE', 'Strategie'),
    _ph('de_h037', 'EISEN ERNTE', 'Strategie'),
    _ph('de_h038', 'GUTER GRUND', 'Aktion'),
    _ph('de_h039', 'VERLORENE ARCHE', 'MMORPG'),
    _ph('de_h040', 'WILDE HERZEN', 'Aktion'),
    _ph('de_h041', 'TAGE VERGANGEN', 'Aktion'),
    _ph('de_h042', 'LINKS TOTE', 'Shooter'),
    _ph('de_h043', 'TOTE INSEL', 'Ueberleben'),
    _ph('de_h044', 'FALL KERLE', 'Party'),
    _ph('de_h045', 'TIEFER FELS', 'Koop'),
    _ph('de_h046', 'BOESE DARIN', 'Horror'),
    _ph('de_h047', 'LEGO STERN', 'Abenteuer'),
    _ph('de_h048', 'SCHATTEN MORDOR', 'Aktion'),
    _ph('de_h049', 'EWIGES VERDERBEN', 'Shooter'),
    _ph('de_h050', 'AEUSSERE WILDNIS', 'Abenteuer'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'de',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'de',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'de',
      );
}
