import '../../data/models/puzzle_model.dart';

/// French puzzle database — Popular video games across all difficulties.
class PuzzlesFr {
  PuzzlesFr._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('fr_e001', 'MARIO', 'Nintendo'),
    _p('fr_e002', 'ZELDA', 'Nintendo'),
    _p('fr_e003', 'SONIC', 'Sega'),
    _p('fr_e004', 'TETRIS', 'Puzzle'),
    _p('fr_e005', 'HADES', 'Roguelike'),
    _p('fr_e006', 'LIMBO', 'Indie'),
    _p('fr_e007', 'DOOM', 'Tir'),
    _p('fr_e008', 'DOTA', 'MOBA'),
    _p('fr_e009', 'HALO', 'Tir'),
    _p('fr_e010', 'PUBG', 'Battle Royale'),
    _p('fr_e011', 'FABLE', 'RPG'),
    _p('fr_e012', 'STRAY', 'Aventure'),
    _p('fr_e013', 'SIFU', 'Combat'),
    _p('fr_e014', 'TUNIC', 'Aventure'),
    _p('fr_e015', 'KIRBY', 'Nintendo'),
    _p('fr_e016', 'SPORE', 'Simulation'),
    _p('fr_e017', 'CRYSIS', 'Tir'),
    _p('fr_e018', 'RUST', 'Survie'),
    _p('fr_e019', 'PREY', 'Tir'),
    _p('fr_e020', 'SOMA', 'Horreur'),
    _p('fr_e021', 'ABZU', 'Aventure'),
    _p('fr_e022', 'MYST', 'Puzzle'),
    _p('fr_e023', 'GRIS', 'Indie'),
    _p('fr_e024', 'OKAMI', 'Action'),
    _p('fr_e025', 'PYRE', 'RPG'),
    _p('fr_e026', 'BRAID', 'Indie'),
    _p('fr_e027', 'SCORN', 'Horreur'),
    _p('fr_e028', 'FURI', 'Action'),
    _p('fr_e029', 'KENA', 'Action'),
    _p('fr_e030', 'EMBER', 'RPG'),
    _p('fr_e031', 'TRINE', 'Puzzle'),
    _p('fr_e032', 'OMORI', 'RPG'),
    _p('fr_e033', 'ATLAS', 'Survie'),
    _p('fr_e034', 'NEON', 'Action'),
    _p('fr_e035', 'HAVEN', 'RPG'),
    _p('fr_e036', 'DISCO', 'RPG'),
    _p('fr_e037', 'NORCO', 'Aventure'),
    _p('fr_e038', 'TOEM', 'Puzzle'),
    _p('fr_e039', 'SABLE', 'Aventure'),
    _p('fr_e040', 'ANNO', 'Strategie'),
    _p('fr_e041', 'WORMS', 'Strategie'),
    _p('fr_e042', 'RISK', 'Strategie'),
    _p('fr_e043', 'LEGO', 'Aventure'),
    _p('fr_e044', 'SIMS', 'Simulation'),
    _p('fr_e045', 'OLIJA', 'Action'),
    _p('fr_e046', 'YOKU', 'Plateforme'),
    _p('fr_e047', 'FEIST', 'Indie'),
    _p('fr_e048', 'EDITH', 'Aventure'),
    _p('fr_e049', 'FLOW', 'Indie'),
    _p('fr_e050', 'RAGE', 'Tir'),
    _p('fr_e051', 'STEEP', 'Sport'),
    _p('fr_e052', 'VIGOR', 'Survie'),
    _p('fr_e053', 'BULLY', 'Action'),
    _p('fr_e054', 'ARMA', 'Simulation'),
    _p('fr_e055', 'RYSE', 'Action'),
    _p('fr_e056', 'RUINER', 'Action'),
    _p('fr_e057', 'INSIDE', 'Indie'),
    _p('fr_e058', 'CUPHEAD', 'Plateforme'),
    _p('fr_e059', 'CELESTE', 'Plateforme'),
    _p('fr_e060', 'VALHEIM', 'Survie'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('fr_m001', 'SKYRIM', 'RPG'),
    _pm('fr_m002', 'PORTAL', 'Puzzle'),
    _pm('fr_m003', 'HITMAN', 'Furtif'),
    _pm('fr_m004', 'DIABLO', 'RPG'),
    _pm('fr_m005', 'FALLOUT', 'RPG'),
    _pm('fr_m006', 'DESTINY', 'Tir'),
    _pm('fr_m007', 'FORTNITE', 'Battle Royale'),
    _pm('fr_m008', 'OVERWATCH', 'Tir'),
    _pm('fr_m009', 'MINECRAFT', 'Sandbox'),
    _pm('fr_m010', 'TERRARIA', 'Sandbox'),
    _pm('fr_m011', 'OUTLAST', 'Horreur'),
    _pm('fr_m012', 'CONTROL', 'Action'),
    _pm('fr_m013', 'BAYONETTA', 'Action'),
    _pm('fr_m014', 'BLOODBORNE', 'RPG'),
    _pm('fr_m015', 'SEKIRO', 'Action'),
    _pm('fr_m016', 'RETURNAL', 'Roguelike'),
    _pm('fr_m017', 'TEKKEN', 'Combat'),
    _pm('fr_m018', 'UNCHARTED', 'Aventure'),
    _pm('fr_m019', 'HORIZON', 'RPG'),
    _pm('fr_m020', 'TITANFALL', 'Tir'),
    _pm('fr_m021', 'WITCHER', 'RPG'),
    _pm('fr_m022', 'CYBERPUNK', 'RPG'),
    _pm('fr_m023', 'SUBNAUTICA', 'Survie'),
    _pm('fr_m024', 'DISHONORED', 'Furtif'),
    _pm('fr_m025', 'METROID', 'Aventure'),
    _pm('fr_m026', 'RAYMAN', 'Plateforme'),
    _pm('fr_m027', 'RATCHET', 'Plateforme'),
    _pm('fr_m028', 'HELLBLADE', 'Action'),
    _pm('fr_m029', 'JOURNEY', 'Indie'),
    _pm('fr_m030', 'FIREWATCH', 'Aventure'),
    _pm('fr_m031', 'UNDERTALE', 'RPG'),
    _pm('fr_m032', 'FACTORIO', 'Simulation'),
    _pm('fr_m033', 'RIMWORLD', 'Simulation'),
    _pm('fr_m034', 'SPLATOON', 'Tir'),
    _pm('fr_m035', 'XENOBLADE', 'RPG'),
    _pm('fr_m036', 'STARFIELD', 'RPG'),
    _pm('fr_m037', 'REMNANT', 'Action'),
    _pm('fr_m038', 'BIOSHOCK', 'Tir'),
    _pm('fr_m039', 'WARCRAFT', 'Strategie'),
    _pm('fr_m040', 'STARCRAFT', 'Strategie'),
    _pm('fr_m041', 'DEATHLOOP', 'Tir'),
    _pm('fr_m042', 'INFAMOUS', 'Action'),
    _pm('fr_m043', 'VAMPYR', 'RPG'),
    _pm('fr_m044', 'NIOH', 'Action'),
    _pm('fr_m045', 'TROPICO', 'Simulation'),
    _pm('fr_m046', 'TEMTEM', 'RPG'),
    _pm('fr_m047', 'DARKEST', 'RPG'),
    _pm('fr_m048', 'HOLLOW', 'Plateforme'),
    _pm('fr_m049', 'BASTION', 'RPG'),
    _pm('fr_m050', 'SPELUNKY', 'Roguelike'),
    _pm('fr_m051', 'ASTRONEER', 'Survie'),
    _pm('fr_m052', 'CHIVALRY', 'Action'),
    _pm('fr_m053', 'GREEDFALL', 'RPG'),
    _pm('fr_m054', 'KENSHI', 'RPG'),
    _pm('fr_m055', 'ARAGAMI', 'Furtif'),
    _pm('fr_m056', 'BIOMUTANT', 'RPG'),
    _pm('fr_m057', 'GHOSTWIRE', 'Action'),
    _pm('fr_m058', 'INSCRYPTION', 'Cartes'),
    _pm('fr_m059', 'OUTRIDERS', 'Tir'),
    _pm('fr_m060', 'MONSTER', 'RPG'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('fr_h001', 'ELDEN RING', 'RPG'),
    _ph('fr_h002', 'DIEU GUERRE', 'Action'),
    _ph('fr_h003', 'AMES SOMBRES', 'RPG'),
    _ph('fr_h004', 'ROUGE MORT', 'Monde Ouvert'),
    _ph('fr_h005', 'DERNIER NOUS', 'Aventure'),
    _ph('fr_h006', 'FINAL FANTASY', 'RPG'),
    _ph('fr_h007', 'EFFET MASSE', 'RPG'),
    _ph('fr_h008', 'ESPACE MORT', 'Horreur'),
    _ph('fr_h009', 'PILLEURS TOMBE', 'Aventure'),
    _ph('fr_h010', 'METAL SOLIDE', 'Furtif'),
    _ph('fr_h011', 'DEMI VIE', 'Tir'),
    _ph('fr_h012', 'MORT ECHOUAGE', 'Aventure'),
    _ph('fr_h013', 'FANTOME RECON', 'Tir'),
    _ph('fr_h014', 'DRAGON AGE', 'RPG'),
    _ph('fr_h015', 'SUPER COMBAT', 'Combat'),
    _ph('fr_h016', 'ANIMAL CROISEMENT', 'Simulation'),
    _ph('fr_h017', 'RUE COMBATTANT', 'Combat'),
    _ph('fr_h018', 'ENGRENAGE GUERRE', 'Tir'),
    _ph('fr_h019', 'FUSEE LIGUE', 'Sport'),
    _ph('fr_h020', 'PRINCE PERSE', 'Action'),
    _ph('fr_h021', 'CHIENS GARDE', 'Monde Ouvert'),
    _ph('fr_h022', 'LUMIERE MOURANTE', 'Horreur'),
    _ph('fr_h023', 'HOMME ARAIGNEE', 'Action'),
    _ph('fr_h024', 'GUERRES ETOILES', 'Action'),
    _ph('fr_h025', 'APPEL DEVOIR', 'Tir'),
    _ph('fr_h026', 'LIGUE LEGENDES', 'MOBA'),
    _ph('fr_h027', 'BALDURS PORTE', 'RPG'),
    _ph('fr_h028', 'LOIN CRI', 'Tir'),
    _ph('fr_h029', 'BESOIN VITESSE', 'Course'),
    _ph('fr_h030', 'VILLES HORIZONS', 'Simulation'),
    _ph('fr_h031', 'DIABLE PLEURE', 'Action'),
    _ph('fr_h032', 'OMBRE COLOSSE', 'Aventure'),
    _ph('fr_h033', 'GUERRE TOTALE', 'Strategie'),
    _ph('fr_h034', 'MER VOLEURS', 'Aventure'),
    _ph('fr_h035', 'SOMMET LEGENDES', 'Battle Royale'),
    _ph('fr_h036', 'AGE EMPIRES', 'Strategie'),
    _ph('fr_h037', 'FER RECOLTE', 'Strategie'),
    _ph('fr_h038', 'JUSTE CAUSE', 'Action'),
    _ph('fr_h039', 'ARCHE PERDUE', 'MMORPG'),
    _ph('fr_h040', 'COEURS SAUVAGES', 'Action'),
    _ph('fr_h041', 'JOURS PARTIS', 'Action'),
    _ph('fr_h042', 'GAUCHE MORT', 'Tir'),
    _ph('fr_h043', 'ILE DES MORTS', 'Survie'),
    _ph('fr_h044', 'GARS TOMBENT', 'Party'),
    _ph('fr_h045', 'ROCHE PROFONDE', 'Coop'),
    _ph('fr_h046', 'MAL DEDANS', 'Horreur'),
    _ph('fr_h047', 'LEGO ETOILES', 'Aventure'),
    _ph('fr_h048', 'OMBRE MORDOR', 'Action'),
    _ph('fr_h049', 'DESTIN ETERNEL', 'Tir'),
    _ph('fr_h050', 'TERRES SAUVAGES', 'Aventure'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'fr',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'fr',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'fr',
      );
}
