import '../../data/models/puzzle_model.dart';

/// German puzzle database — 170+ puzzles across all difficulties.
class PuzzlesDe {
  PuzzlesDe._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('de_e001', 'APFEL', 'Obst'),
    _p('de_e002', 'BIRNE', 'Obst'),
    _p('de_e003', 'TRAUBE', 'Obst'),
    _p('de_e004', 'KIRSCHE', 'Obst'),
    _p('de_e005', 'BANANE', 'Obst'),
    _p('de_e006', 'ZITRONE', 'Obst'),
    _p('de_e007', 'MELONE', 'Obst'),
    _p('de_e008', 'PFLAUME', 'Obst'),
    _p('de_e009', 'MANGO', 'Obst'),
    _p('de_e010', 'BEERE', 'Obst'),
    _p('de_e011', 'KATZE', 'Tiere'),
    _p('de_e012', 'HUND', 'Tiere'),
    _p('de_e013', 'PFERD', 'Tiere'),
    _p('de_e014', 'VOGEL', 'Tiere'),
    _p('de_e015', 'MAUS', 'Tiere'),
    _p('de_e016', 'ADLER', 'Tiere'),
    _p('de_e017', 'TIGER', 'Tiere'),
    _p('de_e018', 'SCHLANGE', 'Tiere'),
    _p('de_e019', 'PANDA', 'Tiere'),
    _p('de_e020', 'FUCHS', 'Tiere'),
    _p('de_e021', 'STUHL', 'Moebel'),
    _p('de_e022', 'TISCH', 'Moebel'),
    _p('de_e023', 'LAMPE', 'Moebel'),
    _p('de_e024', 'REGAL', 'Moebel'),
    _p('de_e025', 'BETT', 'Moebel'),
    _p('de_e026', 'BROT', 'Essen'),
    _p('de_e027', 'MILCH', 'Essen'),
    _p('de_e028', 'SUPPE', 'Essen'),
    _p('de_e029', 'SALAT', 'Essen'),
    _p('de_e030', 'REIS', 'Essen'),
    _p('de_e031', 'WOLKE', 'Natur'),
    _p('de_e032', 'STERN', 'Natur'),
    _p('de_e033', 'FLUSS', 'Natur'),
    _p('de_e034', 'BERG', 'Natur'),
    _p('de_e035', 'WALD', 'Natur'),
    _p('de_e036', 'MEER', 'Natur'),
    _p('de_e037', 'FEUER', 'Natur'),
    _p('de_e038', 'STEIN', 'Natur'),
    _p('de_e039', 'WIND', 'Natur'),
    _p('de_e040', 'REGEN', 'Natur'),
    _p('de_e041', 'BUCH', 'Objekte'),
    _p('de_e042', 'STIFT', 'Objekte'),
    _p('de_e043', 'UHREN', 'Objekte'),
    _p('de_e044', 'KRONE', 'Objekte'),
    _p('de_e045', 'SPIEGEL', 'Objekte'),
    _p('de_e046', 'SCHULE', 'Orte'),
    _p('de_e047', 'HAFEN', 'Orte'),
    _p('de_e048', 'TURM', 'Orte'),
    _p('de_e049', 'GARTEN', 'Orte'),
    _p('de_e050', 'MARKT', 'Orte'),
    _p('de_e051', 'SILBER', 'Metalle'),
    _p('de_e052', 'KUPFER', 'Metalle'),
    _p('de_e053', 'EISEN', 'Metalle'),
    _p('de_e054', 'SEIDE', 'Stoffe'),
    _p('de_e055', 'WOLLE', 'Stoffe'),
    _p('de_e056', 'KLAVIER', 'Musik'),
    _p('de_e057', 'GEIGE', 'Musik'),
    _p('de_e058', 'TROMMEL', 'Musik'),
    _p('de_e059', 'HARFE', 'Musik'),
    _p('de_e060', 'TRAUM', 'Abstrakt'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('de_m001', 'RITTER', 'Fantasie'),
    _pm('de_m002', 'DRACHE', 'Fantasie'),
    _pm('de_m003', 'ZAUBERER', 'Fantasie'),
    _pm('de_m004', 'SCHLOSS', 'Gebaeude'),
    _pm('de_m005', 'PALAST', 'Gebaeude'),
    _pm('de_m006', 'TEMPEL', 'Gebaeude'),
    _pm('de_m007', 'MUSEUM', 'Gebaeude'),
    _pm('de_m008', 'RAKETE', 'Weltraum'),
    _pm('de_m009', 'PLANET', 'Weltraum'),
    _pm('de_m010', 'GALAXIE', 'Weltraum'),
    _pm('de_m011', 'FUSSBALL', 'Sport'),
    _pm('de_m012', 'TENNIS', 'Sport'),
    _pm('de_m013', 'SCHWIMMEN', 'Sport'),
    _pm('de_m014', 'BOXEN', 'Sport'),
    _pm('de_m015', 'GITARRE', 'Musik'),
    _pm('de_m016', 'DIAMANT', 'Edelsteine'),
    _pm('de_m017', 'SMARAGD', 'Edelsteine'),
    _pm('de_m018', 'SAPHIR', 'Edelsteine'),
    _pm('de_m019', 'RUBIN', 'Edelsteine'),
    _pm('de_m020', 'HERBST', 'Jahreszeiten'),
    _pm('de_m021', 'WINTER', 'Jahreszeiten'),
    _pm('de_m022', 'SOMMER', 'Jahreszeiten'),
    _pm('de_m023', 'SCHMETTERLING', 'Tiere'),
    _pm('de_m024', 'PINGUIN', 'Tiere'),
    _pm('de_m025', 'GIRAFFE', 'Tiere'),
    _pm('de_m026', 'DELPHIN', 'Tiere'),
    _pm('de_m027', 'PAPAGEI', 'Tiere'),
    _pm('de_m028', 'FALKE', 'Tiere'),
    _pm('de_m029', 'COMPUTER', 'Technologie'),
    _pm('de_m030', 'ROBOTER', 'Technologie'),
    _pm('de_m031', 'VULKAN', 'Natur'),
    _pm('de_m032', 'ERDBEBEN', 'Natur'),
    _pm('de_m033', 'GEWITTER', 'Natur'),
    _pm('de_m034', 'ARZT', 'Berufe'),
    _pm('de_m035', 'LEHRER', 'Berufe'),
    _pm('de_m036', 'SOLDAT', 'Berufe'),
    _pm('de_m037', 'KAPITAEN', 'Berufe'),
    _pm('de_m038', 'SCHATTEN', 'Abstrakt'),
    _pm('de_m039', 'FREIHEIT', 'Abstrakt'),
    _pm('de_m040', 'ABENTEUER', 'Abstrakt'),
    _pm('de_m041', 'LEGENDE', 'Fantasie'),
    _pm('de_m042', 'KOMPASS', 'Abenteuer'),
    _pm('de_m043', 'LANDKARTE', 'Abenteuer'),
    _pm('de_m044', 'KAFFEE', 'Getraenke'),
    _pm('de_m045', 'SCHOKOLADE', 'Essen'),
    _pm('de_m046', 'PFEFFER', 'Essen'),
    _pm('de_m047', 'BUTTER', 'Essen'),
    _pm('de_m048', 'MARMOR', 'Materialien'),
    _pm('de_m049', 'SAMT', 'Materialien'),
    _pm('de_m050', 'BAUMWOLLE', 'Materialien'),
    _pm('de_m051', 'KRISTALL', 'Mineralien'),
    _pm('de_m052', 'ELEFANT', 'Tiere'),
    _pm('de_m053', 'PANTHER', 'Tiere'),
    _pm('de_m054', 'PHOENIX', 'Mythologie'),
    _pm('de_m055', 'EINHORN', 'Mythologie'),
    _pm('de_m056', 'WIKINGER', 'Geschichte'),
    _pm('de_m057', 'PHARAO', 'Geschichte'),
    _pm('de_m058', 'GLADIATOR', 'Geschichte'),
    _pm('de_m059', 'PIRAT', 'Abenteuer'),
    _pm('de_m060', 'ANKER', 'Seefahrt'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('de_h001', 'SCHWARZER WALD', 'Natur'),
    _ph('de_h002', 'NORD STERN', 'Astronomie'),
    _ph('de_h003', 'MOND LICHT', 'Natur'),
    _ph('de_h004', 'FEUER DRACHE', 'Fantasie'),
    _ph('de_h005', 'EIS SCHLOSS', 'Fantasie'),
    _ph('de_h006', 'STURM WIND', 'Wetter'),
    _ph('de_h007', 'GOLD MINE', 'Bergbau'),
    _ph('de_h008', 'DONNER BLITZ', 'Wetter'),
    _ph('de_h009', 'SILBER MOND', 'Astronomie'),
    _ph('de_h010', 'WILD FEUER', 'Natur'),
    _ph('de_h011', 'SAND STURM', 'Wetter'),
    _ph('de_h012', 'TIEFSEE', 'Natur'),
    _ph('de_h013', 'STERN STAUB', 'Weltraum'),
    _ph('de_h014', 'WOLF RUDEL', 'Tiere'),
    _ph('de_h015', 'GEISTER SCHIFF', 'Mythologie'),
    _ph('de_h016', 'DUNKLER TURM', 'Fantasie'),
    _ph('de_h017', 'KORALLEN RIFF', 'Natur'),
    _ph('de_h018', 'SCHNEE FLOCKE', 'Natur'),
    _ph('de_h019', 'MOND STEIN', 'Edelsteine'),
    _ph('de_h020', 'FLAMMEN SCHWERT', 'Fantasie'),
    _ph('de_h021', 'GROSSE MAUER', 'Wahrzeichen'),
    _ph('de_h022', 'REGEN BOGEN', 'Natur'),
    _ph('de_h023', 'KRISTALL HOEHLE', 'Natur'),
    _ph('de_h024', 'STEIN BRUECKE', 'Bauwerke'),
    _ph('de_h025', 'DUNKEL WALD', 'Natur'),
    _ph('de_h026', 'FEUER VOGEL', 'Mythologie'),
    _ph('de_h027', 'EIS BAER', 'Tiere'),
    _ph('de_h028', 'NACHT FALKE', 'Tiere'),
    _ph('de_h029', 'ROTER DRACHE', 'Fantasie'),
    _ph('de_h030', 'SCHWARZ LOCH', 'Weltraum'),
    _ph('de_h031', 'SONNEN WIND', 'Weltraum'),
    _ph('de_h032', 'WASSER FALL', 'Natur'),
    _ph('de_h033', 'BERG GIPFEL', 'Natur'),
    _ph('de_h034', 'RITTER BURG', 'Geschichte'),
    _ph('de_h035', 'SCHATZ KISTE', 'Abenteuer'),
    _ph('de_h036', 'BLITZ KRIEG', 'Geschichte'),
    _ph('de_h037', 'MOND FINSTERNIS', 'Astronomie'),
    _ph('de_h038', 'ZAUBER STAB', 'Fantasie'),
    _ph('de_h039', 'DRACHEN REITER', 'Fantasie'),
    _ph('de_h040', 'WIND MUEHLE', 'Bauwerke'),
    _ph('de_h041', 'SONNEN AUFGANG', 'Natur'),
    _ph('de_h042', 'SCHNEE STURM', 'Wetter'),
    _ph('de_h043', 'FEUER WERK', 'Feste'),
    _ph('de_h044', 'BURG GRABEN', 'Geschichte'),
    _ph('de_h045', 'LEUCHT TURM', 'Bauwerke'),
    _ph('de_h046', 'NEBEL MEER', 'Natur'),
    _ph('de_h047', 'STURM FLUT', 'Natur'),
    _ph('de_h048', 'GLOCKEN TURM', 'Bauwerke'),
    _ph('de_h049', 'WOLKEN BRUCH', 'Wetter'),
    _ph('de_h050', 'STERNEN NACHT', 'Natur'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'de',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'de',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'de',
      );
}
