import '../../data/models/puzzle_model.dart';

/// Spanish puzzle database — Popular video games across all difficulties.
class PuzzlesEs {
  PuzzlesEs._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('es_e001', 'MARIO', 'Nintendo'),
    _p('es_e002', 'ZELDA', 'Nintendo'),
    _p('es_e003', 'SONIC', 'Sega'),
    _p('es_e004', 'TETRIS', 'Puzzle'),
    _p('es_e005', 'HADES', 'Roguelike'),
    _p('es_e006', 'LIMBO', 'Indie'),
    _p('es_e007', 'DOOM', 'Disparos'),
    _p('es_e008', 'DOTA', 'MOBA'),
    _p('es_e009', 'HALO', 'Disparos'),
    _p('es_e010', 'PUBG', 'Battle Royale'),
    _p('es_e011', 'FABLE', 'RPG'),
    _p('es_e012', 'STRAY', 'Aventura'),
    _p('es_e013', 'SIFU', 'Lucha'),
    _p('es_e014', 'TUNIC', 'Aventura'),
    _p('es_e015', 'KIRBY', 'Nintendo'),
    _p('es_e016', 'SPORE', 'Simulacion'),
    _p('es_e017', 'CRYSIS', 'Disparos'),
    _p('es_e018', 'RUST', 'Supervivencia'),
    _p('es_e019', 'PREY', 'Disparos'),
    _p('es_e020', 'SOMA', 'Terror'),
    _p('es_e021', 'ABZU', 'Aventura'),
    _p('es_e022', 'MYST', 'Puzzle'),
    _p('es_e023', 'GRIS', 'Indie'),
    _p('es_e024', 'OKAMI', 'Accion'),
    _p('es_e025', 'PYRE', 'RPG'),
    _p('es_e026', 'BRAID', 'Indie'),
    _p('es_e027', 'SCORN', 'Terror'),
    _p('es_e028', 'FURI', 'Accion'),
    _p('es_e029', 'KENA', 'Accion'),
    _p('es_e030', 'EMBER', 'RPG'),
    _p('es_e031', 'TRINE', 'Puzzle'),
    _p('es_e032', 'OMORI', 'RPG'),
    _p('es_e033', 'ATLAS', 'Supervivencia'),
    _p('es_e034', 'NEON', 'Accion'),
    _p('es_e035', 'HAVEN', 'RPG'),
    _p('es_e036', 'DISCO', 'RPG'),
    _p('es_e037', 'NORCO', 'Aventura'),
    _p('es_e038', 'TOEM', 'Puzzle'),
    _p('es_e039', 'SABLE', 'Aventura'),
    _p('es_e040', 'ANNO', 'Estrategia'),
    _p('es_e041', 'WORMS', 'Estrategia'),
    _p('es_e042', 'RISK', 'Estrategia'),
    _p('es_e043', 'LEGO', 'Aventura'),
    _p('es_e044', 'SIMS', 'Simulacion'),
    _p('es_e045', 'OLIJA', 'Accion'),
    _p('es_e046', 'YOKU', 'Plataformas'),
    _p('es_e047', 'FEIST', 'Indie'),
    _p('es_e048', 'EDITH', 'Aventura'),
    _p('es_e049', 'FLOW', 'Indie'),
    _p('es_e050', 'RAGE', 'Disparos'),
    _p('es_e051', 'STEEP', 'Deportes'),
    _p('es_e052', 'VIGOR', 'Supervivencia'),
    _p('es_e053', 'BULLY', 'Accion'),
    _p('es_e054', 'ARMA', 'Simulacion'),
    _p('es_e055', 'RYSE', 'Accion'),
    _p('es_e056', 'RUINER', 'Accion'),
    _p('es_e057', 'INSIDE', 'Indie'),
    _p('es_e058', 'CUPHEAD', 'Plataformas'),
    _p('es_e059', 'CELESTE', 'Plataformas'),
    _p('es_e060', 'VALHEIM', 'Supervivencia'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('es_m001', 'SKYRIM', 'RPG'),
    _pm('es_m002', 'PORTAL', 'Puzzle'),
    _pm('es_m003', 'HITMAN', 'Sigilo'),
    _pm('es_m004', 'DIABLO', 'RPG'),
    _pm('es_m005', 'FALLOUT', 'RPG'),
    _pm('es_m006', 'DESTINY', 'Disparos'),
    _pm('es_m007', 'FORTNITE', 'Battle Royale'),
    _pm('es_m008', 'OVERWATCH', 'Disparos'),
    _pm('es_m009', 'MINECRAFT', 'Sandbox'),
    _pm('es_m010', 'TERRARIA', 'Sandbox'),
    _pm('es_m011', 'OUTLAST', 'Terror'),
    _pm('es_m012', 'CONTROL', 'Accion'),
    _pm('es_m013', 'BAYONETTA', 'Accion'),
    _pm('es_m014', 'BLOODBORNE', 'RPG'),
    _pm('es_m015', 'SEKIRO', 'Accion'),
    _pm('es_m016', 'RETURNAL', 'Roguelike'),
    _pm('es_m017', 'TEKKEN', 'Lucha'),
    _pm('es_m018', 'UNCHARTED', 'Aventura'),
    _pm('es_m019', 'HORIZON', 'RPG'),
    _pm('es_m020', 'TITANFALL', 'Disparos'),
    _pm('es_m021', 'WITCHER', 'RPG'),
    _pm('es_m022', 'CYBERPUNK', 'RPG'),
    _pm('es_m023', 'SUBNAUTICA', 'Supervivencia'),
    _pm('es_m024', 'DISHONORED', 'Sigilo'),
    _pm('es_m025', 'METROID', 'Aventura'),
    _pm('es_m026', 'RAYMAN', 'Plataformas'),
    _pm('es_m027', 'RATCHET', 'Plataformas'),
    _pm('es_m028', 'HELLBLADE', 'Accion'),
    _pm('es_m029', 'JOURNEY', 'Indie'),
    _pm('es_m030', 'FIREWATCH', 'Aventura'),
    _pm('es_m031', 'UNDERTALE', 'RPG'),
    _pm('es_m032', 'FACTORIO', 'Simulacion'),
    _pm('es_m033', 'RIMWORLD', 'Simulacion'),
    _pm('es_m034', 'SPLATOON', 'Disparos'),
    _pm('es_m035', 'XENOBLADE', 'RPG'),
    _pm('es_m036', 'STARFIELD', 'RPG'),
    _pm('es_m037', 'REMNANT', 'Accion'),
    _pm('es_m038', 'BIOSHOCK', 'Disparos'),
    _pm('es_m039', 'WARCRAFT', 'Estrategia'),
    _pm('es_m040', 'STARCRAFT', 'Estrategia'),
    _pm('es_m041', 'DEATHLOOP', 'Disparos'),
    _pm('es_m042', 'INFAMOUS', 'Accion'),
    _pm('es_m043', 'VAMPYR', 'RPG'),
    _pm('es_m044', 'NIOH', 'Accion'),
    _pm('es_m045', 'TROPICO', 'Simulacion'),
    _pm('es_m046', 'TEMTEM', 'RPG'),
    _pm('es_m047', 'DARKEST', 'RPG'),
    _pm('es_m048', 'HOLLOW', 'Plataformas'),
    _pm('es_m049', 'BASTION', 'RPG'),
    _pm('es_m050', 'SPELUNKY', 'Roguelike'),
    _pm('es_m051', 'ASTRONEER', 'Supervivencia'),
    _pm('es_m052', 'CHIVALRY', 'Accion'),
    _pm('es_m053', 'GREEDFALL', 'RPG'),
    _pm('es_m054', 'KENSHI', 'RPG'),
    _pm('es_m055', 'ARAGAMI', 'Sigilo'),
    _pm('es_m056', 'BIOMUTANT', 'RPG'),
    _pm('es_m057', 'GHOSTWIRE', 'Accion'),
    _pm('es_m058', 'INSCRYPTION', 'Cartas'),
    _pm('es_m059', 'OUTRIDERS', 'Disparos'),
    _pm('es_m060', 'MONSTER', 'RPG'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('es_h001', 'ELDEN RING', 'RPG'),
    _ph('es_h002', 'DIOS GUERRA', 'Accion'),
    _ph('es_h003', 'ALMAS OSCURAS', 'RPG'),
    _ph('es_h004', 'ROJO MUERTO', 'Mundo Abierto'),
    _ph('es_h005', 'ULTIMO DE NOSOTROS', 'Aventura'),
    _ph('es_h006', 'FINAL FANTASY', 'RPG'),
    _ph('es_h007', 'EFECTO MASA', 'RPG'),
    _ph('es_h008', 'ESPACIO MUERTO', 'Terror'),
    _ph('es_h009', 'TUMBA SAQUEADOR', 'Aventura'),
    _ph('es_h010', 'METAL SOLIDO', 'Sigilo'),
    _ph('es_h011', 'MEDIA VIDA', 'Disparos'),
    _ph('es_h012', 'MUERTE VARADA', 'Aventura'),
    _ph('es_h013', 'FANTASMA RECON', 'Disparos'),
    _ph('es_h014', 'DRAGON EDAD', 'RPG'),
    _ph('es_h015', 'SUPER PELEA', 'Lucha'),
    _ph('es_h016', 'ANIMAL CRUCE', 'Simulacion'),
    _ph('es_h017', 'CALLE LUCHADOR', 'Lucha'),
    _ph('es_h018', 'ENGRANAJE GUERRA', 'Disparos'),
    _ph('es_h019', 'COHETE LIGA', 'Deportes'),
    _ph('es_h020', 'PRINCIPE PERSIA', 'Accion'),
    _ph('es_h021', 'PERROS GUARDIA', 'Mundo Abierto'),
    _ph('es_h022', 'LUZ MORIBUNDA', 'Terror'),
    _ph('es_h023', 'HOMBRE ARANA', 'Accion'),
    _ph('es_h024', 'GUERRAS GALAXIAS', 'Accion'),
    _ph('es_h025', 'LLAMADA DEBER', 'Disparos'),
    _ph('es_h026', 'LIGA LEYENDAS', 'MOBA'),
    _ph('es_h027', 'BALDURS PUERTA', 'RPG'),
    _ph('es_h028', 'LEJOS GRITO', 'Disparos'),
    _ph('es_h029', 'NECESIDAD VELOCIDAD', 'Carreras'),
    _ph('es_h030', 'CIUDADES HORIZONTES', 'Simulacion'),
    _ph('es_h031', 'DIABLO LLORA', 'Accion'),
    _ph('es_h032', 'SOMBRA COLOSO', 'Aventura'),
    _ph('es_h033', 'GUERRA TOTAL', 'Estrategia'),
    _ph('es_h034', 'MAR LADRONES', 'Aventura'),
    _ph('es_h035', 'CUMBRE LEYENDAS', 'Battle Royale'),
    _ph('es_h036', 'EDAD IMPERIOS', 'Estrategia'),
    _ph('es_h037', 'HIERRO COSECHA', 'Estrategia'),
    _ph('es_h038', 'JUSTA CAUSA', 'Accion'),
    _ph('es_h039', 'ARCA PERDIDA', 'MMORPG'),
    _ph('es_h040', 'CORAZONES SALVAJES', 'Accion'),
    _ph('es_h041', 'DIAS PASADOS', 'Accion'),
    _ph('es_h042', 'IZQUIERDA MUERTOS', 'Disparos'),
    _ph('es_h043', 'ISLA MUERTOS', 'Supervivencia'),
    _ph('es_h044', 'CHICOS CAEN', 'Party'),
    _ph('es_h045', 'ROCA PROFUNDA', 'Coop'),
    _ph('es_h046', 'MAL DENTRO', 'Terror'),
    _ph('es_h047', 'LEGO ESTRELLAS', 'Aventura'),
    _ph('es_h048', 'SOMBRA MORDOR', 'Accion'),
    _ph('es_h049', 'DESTINO ETERNO', 'Disparos'),
    _ph('es_h050', 'TIERRAS SALVAJES', 'Aventura'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'es',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'es',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'es',
      );
}
