import '../../data/models/puzzle_model.dart';

/// English puzzle database — 200+ puzzles across all difficulties.
class PuzzlesEn {
  PuzzlesEn._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('en_e001', 'APPLE', 'Fruits'),
    _p('en_e002', 'GRAPE', 'Fruits'),
    _p('en_e003', 'LEMON', 'Fruits'),
    _p('en_e004', 'MELON', 'Fruits'),
    _p('en_e005', 'PEACH', 'Fruits'),
    _p('en_e006', 'MANGO', 'Fruits'),
    _p('en_e007', 'BERRY', 'Fruits'),
    _p('en_e008', 'PLUM', 'Fruits'),
    _p('en_e009', 'PEAR', 'Fruits'),
    _p('en_e010', 'LIME', 'Fruits'),
    _p('en_e011', 'CHAIR', 'Furniture'),
    _p('en_e012', 'TABLE', 'Furniture'),
    _p('en_e013', 'COUCH', 'Furniture'),
    _p('en_e014', 'SHELF', 'Furniture'),
    _p('en_e015', 'STOOL', 'Furniture'),
    _p('en_e016', 'TIGER', 'Animals'),
    _p('en_e017', 'HORSE', 'Animals'),
    _p('en_e018', 'MOUSE', 'Animals'),
    _p('en_e019', 'SNAKE', 'Animals'),
    _p('en_e020', 'EAGLE', 'Animals'),
    _p('en_e021', 'SHARK', 'Animals'),
    _p('en_e022', 'WHALE', 'Animals'),
    _p('en_e023', 'CRANE', 'Animals'),
    _p('en_e024', 'PANDA', 'Animals'),
    _p('en_e025', 'KOALA', 'Animals'),
    _p('en_e026', 'PIANO', 'Music'),
    _p('en_e027', 'DRUMS', 'Music'),
    _p('en_e028', 'FLUTE', 'Music'),
    _p('en_e029', 'VIOLA', 'Music'),
    _p('en_e030', 'BANJO', 'Music'),
    _p('en_e031', 'BEACH', 'Travel'),
    _p('en_e032', 'HOTEL', 'Travel'),
    _p('en_e033', 'TRAIN', 'Travel'),
    _p('en_e034', 'OCEAN', 'Nature'),
    _p('en_e035', 'RIVER', 'Nature'),
    _p('en_e036', 'CLOUD', 'Nature'),
    _p('en_e037', 'STORM', 'Nature'),
    _p('en_e038', 'FLAME', 'Nature'),
    _p('en_e039', 'STONE', 'Nature'),
    _p('en_e040', 'EARTH', 'Nature'),
    _p('en_e041', 'BREAD', 'Food'),
    _p('en_e042', 'CHEESE', 'Food'),
    _p('en_e043', 'STEAK', 'Food'),
    _p('en_e044', 'PASTA', 'Food'),
    _p('en_e045', 'SALAD', 'Food'),
    _p('en_e046', 'JUICE', 'Drinks'),
    _p('en_e047', 'WATER', 'Drinks'),
    _p('en_e048', 'CROWN', 'Objects'),
    _p('en_e049', 'SWORD', 'Objects'),
    _p('en_e050', 'SHIELD', 'Objects'),
    _p('en_e051', 'BLOOM', 'Nature'),
    _p('en_e052', 'BRUSH', 'Art'),
    _p('en_e053', 'PAINT', 'Art'),
    _p('en_e054', 'FRAME', 'Art'),
    _p('en_e055', 'DANCE', 'Activities'),
    _p('en_e056', 'CLIMB', 'Activities'),
    _p('en_e057', 'DREAM', 'Abstract'),
    _p('en_e058', 'LIGHT', 'Nature'),
    _p('en_e059', 'MAGIC', 'Fantasy'),
    _p('en_e060', 'FROST', 'Nature'),
    _p('en_e061', 'SMILE', 'Emotions'),
    _p('en_e062', 'HEART', 'Body'),
    _p('en_e063', 'BRAIN', 'Body'),
    _p('en_e064', 'CHEST', 'Body'),
    _p('en_e065', 'GLOBE', 'Objects'),
    _p('en_e066', 'CLOCK', 'Objects'),
    _p('en_e067', 'TOWER', 'Buildings'),
    _p('en_e068', 'BRIDGE', 'Buildings'),
    _p('en_e069', 'CABIN', 'Buildings'),
    _p('en_e070', 'MAPLE', 'Trees'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('en_m001', 'CASTLE', 'Buildings'),
    _pm('en_m002', 'DRAGON', 'Fantasy'),
    _pm('en_m003', 'KNIGHT', 'Fantasy'),
    _pm('en_m004', 'WIZARD', 'Fantasy'),
    _pm('en_m005', 'PIRATE', 'Adventure'),
    _pm('en_m006', 'ANCHOR', 'Nautical'),
    _pm('en_m007', 'ROCKET', 'Space'),
    _pm('en_m008', 'PLANET', 'Space'),
    _pm('en_m009', 'GALAXY', 'Space'),
    _pm('en_m010', 'METEOR', 'Space'),
    _pm('en_m011', 'PYTHON', 'Technology'),
    _pm('en_m012', 'LAPTOP', 'Technology'),
    _pm('en_m013', 'GUITAR', 'Music'),
    _pm('en_m014', 'VIOLIN', 'Music'),
    _pm('en_m015', 'TROPHY', 'Sports'),
    _pm('en_m016', 'SOCCER', 'Sports'),
    _pm('en_m017', 'TENNIS', 'Sports'),
    _pm('en_m018', 'HOCKEY', 'Sports'),
    _pm('en_m019', 'BOXING', 'Sports'),
    _pm('en_m020', 'CANDLE', 'Objects'),
    _pm('en_m021', 'MIRROR', 'Objects'),
    _pm('en_m022', 'GARDEN', 'Nature'),
    _pm('en_m023', 'FOREST', 'Nature'),
    _pm('en_m024', 'DESERT', 'Nature'),
    _pm('en_m025', 'ISLAND', 'Geography'),
    _pm('en_m026', 'CANYON', 'Geography'),
    _pm('en_m027', 'JUNGLE', 'Nature'),
    _pm('en_m028', 'WINTER', 'Seasons'),
    _pm('en_m029', 'SUMMER', 'Seasons'),
    _pm('en_m030', 'SPRING', 'Seasons'),
    _pm('en_m031', 'AUTUMN', 'Seasons'),
    _pm('en_m032', 'SHADOW', 'Abstract'),
    _pm('en_m033', 'SPIRIT', 'Abstract'),
    _pm('en_m034', 'BREEZE', 'Nature'),
    _pm('en_m035', 'SUNSET', 'Nature'),
    _pm('en_m036', 'OXYGEN', 'Science'),
    _pm('en_m037', 'CARBON', 'Science'),
    _pm('en_m038', 'COPPER', 'Science'),
    _pm('en_m039', 'SILVER', 'Science'),
    _pm('en_m040', 'BRONZE', 'Science'),
    _pm('en_m041', 'MARBLE', 'Materials'),
    _pm('en_m042', 'VELVET', 'Materials'),
    _pm('en_m043', 'COTTON', 'Materials'),
    _pm('en_m044', 'COFFEE', 'Drinks'),
    _pm('en_m045', 'BUTTER', 'Food'),
    _pm('en_m046', 'PEPPER', 'Food'),
    _pm('en_m047', 'CHERRY', 'Fruits'),
    _pm('en_m048', 'BANANA', 'Fruits'),
    _pm('en_m049', 'ORANGE', 'Fruits'),
    _pm('en_m050', 'FALCON', 'Animals'),
    _pm('en_m051', 'PARROT', 'Animals'),
    _pm('en_m052', 'JAGUAR', 'Animals'),
    _pm('en_m053', 'WALRUS', 'Animals'),
    _pm('en_m054', 'TEMPLE', 'Buildings'),
    _pm('en_m055', 'PALACE', 'Buildings'),
    _pm('en_m056', 'MUSEUM', 'Buildings'),
    _pm('en_m057', 'HARBOR', 'Places'),
    _pm('en_m058', 'MARKET', 'Places'),
    _pm('en_m059', 'PRISON', 'Buildings'),
    _pm('en_m060', 'THRONE', 'Fantasy'),
    _pm('en_m061', 'SORCERY', 'Fantasy'),
    _pm('en_m062', 'VOYAGE', 'Travel'),
    _pm('en_m063', 'SUMMIT', 'Nature'),
    _pm('en_m064', 'EMERALD', 'Gems'),
    _pm('en_m065', 'DIAMOND', 'Gems'),
    _pm('en_m066', 'SAPPHIRE', 'Gems'),
    _pm('en_m067', 'CAPTAIN', 'Roles'),
    _pm('en_m068', 'SOLDIER', 'Roles'),
    _pm('en_m069', 'SCHOLAR', 'Roles'),
    _pm('en_m070', 'PHOENIX', 'Mythology'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('en_h001', 'GRAND PIANO', 'Music'),
    _ph('en_h002', 'DARK KNIGHT', 'Movies'),
    _ph('en_h003', 'ELDEN RING', 'Video Games'),
    _ph('en_h004', 'IRON MAN', 'Movies'),
    _ph('en_h005', 'STAR WARS', 'Movies'),
    _ph('en_h006', 'LORD RINGS', 'Movies'),
    _ph('en_h007', 'OCEAN WAVE', 'Nature'),
    _ph('en_h008', 'NORTH STAR', 'Astronomy'),
    _ph('en_h009', 'GOLD RUSH', 'History'),
    _ph('en_h010', 'BLUE WHALE', 'Animals'),
    _ph('en_h011', 'BLACK HOLE', 'Space'),
    _ph('en_h012', 'SOLAR WIND', 'Space'),
    _ph('en_h013', 'NIGHT HAWK', 'Animals'),
    _ph('en_h014', 'KING COBRA', 'Animals'),
    _ph('en_h015', 'POLAR BEAR', 'Animals'),
    _ph('en_h016', 'RED DRAGON', 'Fantasy'),
    _ph('en_h017', 'ICE STORM', 'Weather'),
    _ph('en_h018', 'WILD FIRE', 'Nature'),
    _ph('en_h019', 'SAND STORM', 'Weather'),
    _ph('en_h020', 'MOON LIGHT', 'Nature'),
    _ph('en_h021', 'DARK TOWER', 'Literature'),
    _ph('en_h022', 'GHOST SHIP', 'Mythology'),
    _ph('en_h023', 'IRON FORGE', 'Crafting'),
    _ph('en_h024', 'CRYSTAL CAVE', 'Nature'),
    _ph('en_h025', 'THUNDER BOLT', 'Weather'),
    _ph('en_h026', 'FROZEN LAKE', 'Nature'),
    _ph('en_h027', 'SILVER MOON', 'Astronomy'),
    _ph('en_h028', 'CORAL REEF', 'Nature'),
    _ph('en_h029', 'STORM CLOUD', 'Weather'),
    _ph('en_h030', 'BRAVE HEART', 'Movies'),
    _ph('en_h031', 'GREAT WALL', 'Landmarks'),
    _ph('en_h032', 'DEEP OCEAN', 'Nature'),
    _ph('en_h033', 'STONE BRIDGE', 'Structures'),
    _ph('en_h034', 'FLAME SWORD', 'Fantasy'),
    _ph('en_h035', 'DARK FOREST', 'Nature'),
    _ph('en_h036', 'SNOW PEAK', 'Nature'),
    _ph('en_h037', 'LOST TEMPLE', 'Adventure'),
    _ph('en_h038', 'WIND BLADE', 'Fantasy'),
    _ph('en_h039', 'FIRE DRAKE', 'Fantasy'),
    _ph('en_h040', 'HAWK EYE', 'Movies'),
    _ph('en_h041', 'GOLD MINE', 'Mining'),
    _ph('en_h042', 'SILK ROAD', 'History'),
    _ph('en_h043', 'CAPE HORN', 'Geography'),
    _ph('en_h044', 'PALM TREE', 'Nature'),
    _ph('en_h045', 'RAIN DROP', 'Nature'),
    _ph('en_h046', 'CLOUD NINE', 'Expressions'),
    _ph('en_h047', 'QUICK SAND', 'Nature'),
    _ph('en_h048', 'DAWN LIGHT', 'Nature'),
    _ph('en_h049', 'BOOK WORM', 'Expressions'),
    _ph('en_h050', 'SNOW FLAKE', 'Nature'),
    _ph('en_h051', 'STAR DUST', 'Space'),
    _ph('en_h052', 'GRAND TOUR', 'Travel'),
    _ph('en_h053', 'FIRE STORM', 'Weather'),
    _ph('en_h054', 'ICE CASTLE', 'Fantasy'),
    _ph('en_h055', 'MOON STONE', 'Gems'),
    _ph('en_h056', 'RIVER BANK', 'Nature'),
    _ph('en_h057', 'WOLF PACK', 'Animals'),
    _ph('en_h058', 'CHAIN MAIL', 'Medieval'),
    _ph('en_h059', 'SWORD FISH', 'Animals'),
    _ph('en_h060', 'TRAP DOOR', 'Objects'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'en',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'en',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'en',
      );
}
