import '../../data/models/puzzle_model.dart';

/// English puzzle database — Popular video games across all difficulties.
class PuzzlesEn {
  PuzzlesEn._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('en_e001', 'MARIO', 'Nintendo'),
    _p('en_e002', 'ZELDA', 'Nintendo'),
    _p('en_e003', 'SONIC', 'Sega'),
    _p('en_e004', 'TETRIS', 'Puzzle'),
    _p('en_e005', 'HADES', 'Roguelike'),
    _p('en_e006', 'LIMBO', 'Indie'),
    _p('en_e007', 'BRAID', 'Indie'),
    _p('en_e008', 'DOOM', 'FPS'),
    _p('en_e009', 'DOTA', 'MOBA'),
    _p('en_e010', 'FIFA', 'Sports'),
    _p('en_e011', 'HALO', 'FPS'),
    _p('en_e012', 'PUBG', 'Battle Royale'),
    _p('en_e013', 'RUST', 'Survival'),
    _p('en_e014', 'PREY', 'FPS'),
    _p('en_e015', 'RAGE', 'FPS'),
    _p('en_e016', 'RYSE', 'Action'),
    _p('en_e017', 'FABLE', 'RPG'),
    _p('en_e018', 'TUNIC', 'Adventure'),
    _p('en_e019', 'SIFU', 'Fighting'),
    _p('en_e020', 'STRAY', 'Adventure'),
    _p('en_e021', 'CELESTE', 'Platformer'),
    _p('en_e022', 'KIRBY', 'Nintendo'),
    _p('en_e023', 'SPORE', 'Simulation'),
    _p('en_e024', 'SIMS', 'Simulation'),
    _p('en_e025', 'CRYSIS', 'FPS'),
    _p('en_e026', 'STEEP', 'Sports'),
    _p('en_e027', 'VIGOR', 'Survival'),
    _p('en_e028', 'SCORN', 'Horror'),
    _p('en_e029', 'FURI', 'Action'),
    _p('en_e030', 'ABZU', 'Adventure'),
    _p('en_e031', 'FLOW', 'Indie'),
    _p('en_e032', 'MYST', 'Puzzle'),
    _p('en_e033', 'RUSE', 'Strategy'),
    _p('en_e034', 'ANNO', 'Strategy'),
    _p('en_e035', 'GRIS', 'Indie'),
    _p('en_e036', 'OKAMI', 'Action'),
    _p('en_e037', 'LEGO', 'Adventure'),
    _p('en_e038', 'RISK', 'Strategy'),
    _p('en_e039', 'WORMS', 'Strategy'),
    _p('en_e040', 'PYRE', 'RPG'),
    _p('en_e041', 'CUPHEAD', 'Platformer'),
    _p('en_e042', 'BULLY', 'Action'),
    _p('en_e043', 'SABLE', 'Adventure'),
    _p('en_e044', 'OUTER', 'Adventure'),
    _p('en_e045', 'MORTA', 'RPG'),
    _p('en_e046', 'CARTO', 'Puzzle'),
    _p('en_e047', 'GHOST', 'Action'),
    _p('en_e048', 'ARMA', 'Simulation'),
    _p('en_e049', 'HAVEN', 'RPG'),
    _p('en_e050', 'NEON', 'Action'),
    _p('en_e051', 'OMORI', 'RPG'),
    _p('en_e052', 'BUGSNAX', 'Adventure'),
    _p('en_e053', 'YOKU', 'Platformer'),
    _p('en_e054', 'NORCO', 'Adventure'),
    _p('en_e055', 'TOEM', 'Puzzle'),
    _p('en_e056', 'KENA', 'Action'),
    _p('en_e057', 'OLIJA', 'Action'),
    _p('en_e058', 'VALHEIM', 'Survival'),
    _p('en_e059', 'EMBER', 'RPG'),
    _p('en_e060', 'ATLAS', 'Survival'),
    _p('en_e061', 'SOMA', 'Horror'),
    _p('en_e062', 'OXENFREE', 'Adventure'),
    _p('en_e063', 'RUINER', 'Action'),
    _p('en_e064', 'PIKUNIKU', 'Indie'),
    _p('en_e065', 'INSIDE', 'Indie'),
    _p('en_e066', 'FEIST', 'Indie'),
    _p('en_e067', 'TRINE', 'Puzzle'),
    _p('en_e068', 'EDITH', 'Adventure'),
    _p('en_e069', 'DISCO', 'RPG'),
    _p('en_e070', 'KATANA', 'Action'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('en_m001', 'SKYRIM', 'RPG'),
    _pm('en_m002', 'PORTAL', 'Puzzle'),
    _pm('en_m003', 'HITMAN', 'Stealth'),
    _pm('en_m004', 'DIABLO', 'RPG'),
    _pm('en_m005', 'BIOSHOCK', 'FPS'),
    _pm('en_m006', 'FALLOUT', 'RPG'),
    _pm('en_m007', 'DESTINY', 'FPS'),
    _pm('en_m008', 'WARCRAFT', 'Strategy'),
    _pm('en_m009', 'STARCRAFT', 'Strategy'),
    _pm('en_m010', 'FORTNITE', 'Battle Royale'),
    _pm('en_m011', 'OVERWATCH', 'FPS'),
    _pm('en_m012', 'MINECRAFT', 'Sandbox'),
    _pm('en_m013', 'TERRARIA', 'Sandbox'),
    _pm('en_m014', 'OUTLAST', 'Horror'),
    _pm('en_m015', 'CONTROL', 'Action'),
    _pm('en_m016', 'DEATHLOOP', 'FPS'),
    _pm('en_m017', 'BAYONETTA', 'Action'),
    _pm('en_m018', 'BLOODBORNE', 'RPG'),
    _pm('en_m019', 'SEKIRO', 'Action'),
    _pm('en_m020', 'RETURNAL', 'Roguelike'),
    _pm('en_m021', 'TEKKEN', 'Fighting'),
    _pm('en_m022', 'RESIDENT', 'Horror'),
    _pm('en_m023', 'MORTAL', 'Fighting'),
    _pm('en_m024', 'UNCHARTED', 'Adventure'),
    _pm('en_m025', 'HORIZON', 'RPG'),
    _pm('en_m026', 'TITANFALL', 'FPS'),
    _pm('en_m027', 'MONSTER', 'RPG'),
    _pm('en_m028', 'WITCHER', 'RPG'),
    _pm('en_m029', 'CYBERPUNK', 'RPG'),
    _pm('en_m030', 'SUBNAUTICA', 'Survival'),
    _pm('en_m031', 'PSYCHONAUTS', 'Platformer'),
    _pm('en_m032', 'DISHONORED', 'Stealth'),
    _pm('en_m033', 'BORDERLANDS', 'FPS'),
    _pm('en_m034', 'METROID', 'Adventure'),
    _pm('en_m035', 'RAYMAN', 'Platformer'),
    _pm('en_m036', 'RATCHET', 'Platformer'),
    _pm('en_m037', 'INFAMOUS', 'Action'),
    _pm('en_m038', 'HELLBLADE', 'Action'),
    _pm('en_m039', 'JOURNEY', 'Indie'),
    _pm('en_m040', 'FIREWATCH', 'Adventure'),
    _pm('en_m041', 'UNDERTALE', 'RPG'),
    _pm('en_m042', 'FACTORIO', 'Simulation'),
    _pm('en_m043', 'RIMWORLD', 'Simulation'),
    _pm('en_m044', 'SPLATOON', 'Shooter'),
    _pm('en_m045', 'XENOBLADE', 'RPG'),
    _pm('en_m046', 'STARFIELD', 'RPG'),
    _pm('en_m047', 'OUTRIDERS', 'Shooter'),
    _pm('en_m048', 'REMNANT', 'Action'),
    _pm('en_m049', 'INSCRYPTION', 'Card Game'),
    _pm('en_m050', 'GHOSTWIRE', 'Action'),
    _pm('en_m051', 'BIOMUTANT', 'RPG'),
    _pm('en_m052', 'ARAGAMI', 'Stealth'),
    _pm('en_m053', 'GREEDFALL', 'RPG'),
    _pm('en_m054', 'VAMPYR', 'RPG'),
    _pm('en_m055', 'NIOH', 'Action'),
    _pm('en_m056', 'KENSHI', 'RPG'),
    _pm('en_m057', 'TROPICO', 'Simulation'),
    _pm('en_m058', 'TEMTEM', 'RPG'),
    _pm('en_m059', 'CHIVALRY', 'Action'),
    _pm('en_m060', 'DARKEST', 'RPG'),
    _pm('en_m061', 'HOLLOW', 'Platformer'),
    _pm('en_m062', 'SHOVEL', 'Platformer'),
    _pm('en_m063', 'BASTION', 'RPG'),
    _pm('en_m064', 'TRANSISTOR', 'RPG'),
    _pm('en_m065', 'SPELUNKY', 'Roguelike'),
    _pm('en_m066', 'BROFORCE', 'Platformer'),
    _pm('en_m067', 'VAMPIRES', 'Survival'),
    _pm('en_m068', 'ASTRONEER', 'Survival'),
    _pm('en_m069', 'SATISFACTORY', 'Simulation'),
    _pm('en_m070', 'PALWORLD', 'Survival'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('en_h001', 'ELDEN RING', 'RPG'),
    _ph('en_h002', 'GOD OF WAR', 'Action'),
    _ph('en_h003', 'DARK SOULS', 'RPG'),
    _ph('en_h004', 'RED DEAD', 'Open World'),
    _ph('en_h005', 'LAST OF US', 'Adventure'),
    _ph('en_h006', 'FINAL FANTASY', 'RPG'),
    _ph('en_h007', 'MASS EFFECT', 'RPG'),
    _ph('en_h008', 'DEAD SPACE', 'Horror'),
    _ph('en_h009', 'TOMB RAIDER', 'Adventure'),
    _ph('en_h010', 'METAL GEAR', 'Stealth'),
    _ph('en_h011', 'HALF LIFE', 'FPS'),
    _ph('en_h012', 'GRAN TURISMO', 'Racing'),
    _ph('en_h013', 'DEATH STRANDING', 'Adventure'),
    _ph('en_h014', 'GHOST RECON', 'Shooter'),
    _ph('en_h015', 'DRAGON AGE', 'RPG'),
    _ph('en_h016', 'SUPER SMASH', 'Fighting'),
    _ph('en_h017', 'ANIMAL CROSSING', 'Simulation'),
    _ph('en_h018', 'STREET FIGHTER', 'Fighting'),
    _ph('en_h019', 'GEARS OF WAR', 'Shooter'),
    _ph('en_h020', 'ROCKET LEAGUE', 'Sports'),
    _ph('en_h021', 'CRASH BANDICOOT', 'Platformer'),
    _ph('en_h022', 'PRINCE PERSIA', 'Action'),
    _ph('en_h023', 'WATCH DOGS', 'Open World'),
    _ph('en_h024', 'DYING LIGHT', 'Horror'),
    _ph('en_h025', 'SPIDER MAN', 'Action'),
    _ph('en_h026', 'STAR WARS', 'Action'),
    _ph('en_h027', 'CALL OF DUTY', 'FPS'),
    _ph('en_h028', 'LEAGUE LEGENDS', 'MOBA'),
    _ph('en_h029', 'WORLD WARCRAFT', 'MMORPG'),
    _ph('en_h030', 'BALDURS GATE', 'RPG'),
    _ph('en_h031', 'FAR CRY', 'FPS'),
    _ph('en_h032', 'NEED SPEED', 'Racing'),
    _ph('en_h033', 'CITIES SKYLINES', 'Simulation'),
    _ph('en_h034', 'DEVIL MAY CRY', 'Action'),
    _ph('en_h035', 'SHADOW COLOSSUS', 'Adventure'),
    _ph('en_h036', 'TOTAL WAR', 'Strategy'),
    _ph('en_h037', 'SEA OF THIEVES', 'Adventure'),
    _ph('en_h038', 'NO MANS SKY', 'Survival'),
    _ph('en_h039', 'APEX LEGENDS', 'Battle Royale'),
    _ph('en_h040', 'AGE EMPIRES', 'Strategy'),
    _ph('en_h041', 'IRON HARVEST', 'Strategy'),
    _ph('en_h042', 'JUST CAUSE', 'Action'),
    _ph('en_h043', 'LOST ARK', 'MMORPG'),
    _ph('en_h044', 'WILD HEARTS', 'Action'),
    _ph('en_h045', 'DAYS GONE', 'Action'),
    _ph('en_h046', 'LEFT DEAD', 'FPS'),
    _ph('en_h047', 'DEAD ISLAND', 'Survival'),
    _ph('en_h048', 'FALL GUYS', 'Party'),
    _ph('en_h049', 'DEEP ROCK', 'Co-op'),
    _ph('en_h050', 'EVIL WITHIN', 'Horror'),
    _ph('en_h051', 'BACK BLOOD', 'FPS'),
    _ph('en_h052', 'LEGO STAR', 'Adventure'),
    _ph('en_h053', 'SHADOW MORDOR', 'Action'),
    _ph('en_h054', 'DOOM ETERNAL', 'FPS'),
    _ph('en_h055', 'ATLAS FALLEN', 'Action'),
    _ph('en_h056', 'CULT LAMB', 'Roguelike'),
    _ph('en_h057', 'CHILD LIGHT', 'RPG'),
    _ph('en_h058', 'OUTER WILDS', 'Adventure'),
    _ph('en_h059', 'ROGUE LEGACY', 'Roguelike'),
    _ph('en_h060', 'HALO INFINITE', 'FPS'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'en',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'en',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'en',
      );
}
