import '../../data/models/puzzle_model.dart';

/// Italian puzzle database — Popular video games across all difficulties.
class PuzzlesIt {
  PuzzlesIt._();

  static List<PuzzleModel> get all => [..._easy, ..._medium, ..._hard];

  static final List<PuzzleModel> _easy = [
    _p('it_e001', 'MARIO', 'Nintendo'),
    _p('it_e002', 'ZELDA', 'Nintendo'),
    _p('it_e003', 'SONIC', 'Sega'),
    _p('it_e004', 'TETRIS', 'Puzzle'),
    _p('it_e005', 'HADES', 'Roguelike'),
    _p('it_e006', 'LIMBO', 'Indie'),
    _p('it_e007', 'DOOM', 'Sparatutto'),
    _p('it_e008', 'DOTA', 'MOBA'),
    _p('it_e009', 'HALO', 'Sparatutto'),
    _p('it_e010', 'PUBG', 'Battle Royale'),
    _p('it_e011', 'FABLE', 'GDR'),
    _p('it_e012', 'STRAY', 'Avventura'),
    _p('it_e013', 'SIFU', 'Combattimento'),
    _p('it_e014', 'TUNIC', 'Avventura'),
    _p('it_e015', 'KIRBY', 'Nintendo'),
    _p('it_e016', 'SPORE', 'Simulazione'),
    _p('it_e017', 'CRYSIS', 'Sparatutto'),
    _p('it_e018', 'RUST', 'Sopravvivenza'),
    _p('it_e019', 'PREY', 'Sparatutto'),
    _p('it_e020', 'SOMA', 'Orrore'),
    _p('it_e021', 'ABZU', 'Avventura'),
    _p('it_e022', 'MYST', 'Puzzle'),
    _p('it_e023', 'GRIS', 'Indie'),
    _p('it_e024', 'OKAMI', 'Azione'),
    _p('it_e025', 'PYRE', 'GDR'),
    _p('it_e026', 'BRAID', 'Indie'),
    _p('it_e027', 'SCORN', 'Orrore'),
    _p('it_e028', 'FURI', 'Azione'),
    _p('it_e029', 'KENA', 'Azione'),
    _p('it_e030', 'EMBER', 'GDR'),
    _p('it_e031', 'TRINE', 'Puzzle'),
    _p('it_e032', 'OMORI', 'GDR'),
    _p('it_e033', 'ATLAS', 'Sopravvivenza'),
    _p('it_e034', 'NEON', 'Azione'),
    _p('it_e035', 'HAVEN', 'GDR'),
    _p('it_e036', 'DISCO', 'GDR'),
    _p('it_e037', 'NORCO', 'Avventura'),
    _p('it_e038', 'TOEM', 'Puzzle'),
    _p('it_e039', 'SABLE', 'Avventura'),
    _p('it_e040', 'ANNO', 'Strategia'),
    _p('it_e041', 'WORMS', 'Strategia'),
    _p('it_e042', 'RISK', 'Strategia'),
    _p('it_e043', 'LEGO', 'Avventura'),
    _p('it_e044', 'SIMS', 'Simulazione'),
    _p('it_e045', 'OLIJA', 'Azione'),
    _p('it_e046', 'YOKU', 'Piattaforma'),
    _p('it_e047', 'FEIST', 'Indie'),
    _p('it_e048', 'EDITH', 'Avventura'),
    _p('it_e049', 'FLOW', 'Indie'),
    _p('it_e050', 'RAGE', 'Sparatutto'),
    _p('it_e051', 'STEEP', 'Sport'),
    _p('it_e052', 'VIGOR', 'Sopravvivenza'),
    _p('it_e053', 'BULLY', 'Azione'),
    _p('it_e054', 'ARMA', 'Simulazione'),
    _p('it_e055', 'RYSE', 'Azione'),
    _p('it_e056', 'RUINER', 'Azione'),
    _p('it_e057', 'INSIDE', 'Indie'),
    _p('it_e058', 'CUPHEAD', 'Piattaforma'),
    _p('it_e059', 'CELESTE', 'Piattaforma'),
    _p('it_e060', 'VALHEIM', 'Sopravvivenza'),
  ];

  static final List<PuzzleModel> _medium = [
    _pm('it_m001', 'SKYRIM', 'GDR'),
    _pm('it_m002', 'PORTAL', 'Puzzle'),
    _pm('it_m003', 'HITMAN', 'Furtivo'),
    _pm('it_m004', 'DIABLO', 'GDR'),
    _pm('it_m005', 'FALLOUT', 'GDR'),
    _pm('it_m006', 'DESTINY', 'Sparatutto'),
    _pm('it_m007', 'FORTNITE', 'Battle Royale'),
    _pm('it_m008', 'OVERWATCH', 'Sparatutto'),
    _pm('it_m009', 'MINECRAFT', 'Sandbox'),
    _pm('it_m010', 'TERRARIA', 'Sandbox'),
    _pm('it_m011', 'OUTLAST', 'Orrore'),
    _pm('it_m012', 'CONTROL', 'Azione'),
    _pm('it_m013', 'BAYONETTA', 'Azione'),
    _pm('it_m014', 'BLOODBORNE', 'GDR'),
    _pm('it_m015', 'SEKIRO', 'Azione'),
    _pm('it_m016', 'RETURNAL', 'Roguelike'),
    _pm('it_m017', 'TEKKEN', 'Combattimento'),
    _pm('it_m018', 'UNCHARTED', 'Avventura'),
    _pm('it_m019', 'HORIZON', 'GDR'),
    _pm('it_m020', 'TITANFALL', 'Sparatutto'),
    _pm('it_m021', 'WITCHER', 'GDR'),
    _pm('it_m022', 'CYBERPUNK', 'GDR'),
    _pm('it_m023', 'SUBNAUTICA', 'Sopravvivenza'),
    _pm('it_m024', 'DISHONORED', 'Furtivo'),
    _pm('it_m025', 'METROID', 'Avventura'),
    _pm('it_m026', 'RAYMAN', 'Piattaforma'),
    _pm('it_m027', 'RATCHET', 'Piattaforma'),
    _pm('it_m028', 'HELLBLADE', 'Azione'),
    _pm('it_m029', 'JOURNEY', 'Indie'),
    _pm('it_m030', 'FIREWATCH', 'Avventura'),
    _pm('it_m031', 'UNDERTALE', 'GDR'),
    _pm('it_m032', 'FACTORIO', 'Simulazione'),
    _pm('it_m033', 'RIMWORLD', 'Simulazione'),
    _pm('it_m034', 'SPLATOON', 'Sparatutto'),
    _pm('it_m035', 'XENOBLADE', 'GDR'),
    _pm('it_m036', 'STARFIELD', 'GDR'),
    _pm('it_m037', 'REMNANT', 'Azione'),
    _pm('it_m038', 'BIOSHOCK', 'Sparatutto'),
    _pm('it_m039', 'WARCRAFT', 'Strategia'),
    _pm('it_m040', 'STARCRAFT', 'Strategia'),
    _pm('it_m041', 'DEATHLOOP', 'Sparatutto'),
    _pm('it_m042', 'INFAMOUS', 'Azione'),
    _pm('it_m043', 'VAMPYR', 'GDR'),
    _pm('it_m044', 'NIOH', 'Azione'),
    _pm('it_m045', 'TROPICO', 'Simulazione'),
    _pm('it_m046', 'TEMTEM', 'GDR'),
    _pm('it_m047', 'DARKEST', 'GDR'),
    _pm('it_m048', 'HOLLOW', 'Piattaforma'),
    _pm('it_m049', 'BASTION', 'GDR'),
    _pm('it_m050', 'SPELUNKY', 'Roguelike'),
    _pm('it_m051', 'ASTRONEER', 'Sopravvivenza'),
    _pm('it_m052', 'CHIVALRY', 'Azione'),
    _pm('it_m053', 'GREEDFALL', 'GDR'),
    _pm('it_m054', 'KENSHI', 'GDR'),
    _pm('it_m055', 'ARAGAMI', 'Furtivo'),
    _pm('it_m056', 'BIOMUTANT', 'GDR'),
    _pm('it_m057', 'GHOSTWIRE', 'Azione'),
    _pm('it_m058', 'INSCRYPTION', 'Carte'),
    _pm('it_m059', 'OUTRIDERS', 'Sparatutto'),
    _pm('it_m060', 'MONSTER', 'GDR'),
  ];

  static final List<PuzzleModel> _hard = [
    _ph('it_h001', 'ELDEN RING', 'GDR'),
    _ph('it_h002', 'DIO GUERRA', 'Azione'),
    _ph('it_h003', 'ANIME OSCURE', 'GDR'),
    _ph('it_h004', 'ROSSO MORTO', 'Mondo Aperto'),
    _ph('it_h005', 'ULTIMO DI NOI', 'Avventura'),
    _ph('it_h006', 'FINAL FANTASY', 'GDR'),
    _ph('it_h007', 'EFFETTO MASSA', 'GDR'),
    _ph('it_h008', 'SPAZIO MORTO', 'Orrore'),
    _ph('it_h009', 'TOMBA PREDONE', 'Avventura'),
    _ph('it_h010', 'METALLO SOLIDO', 'Furtivo'),
    _ph('it_h011', 'MEZZA VITA', 'Sparatutto'),
    _ph('it_h012', 'MORTE FILAMENTO', 'Avventura'),
    _ph('it_h013', 'FANTASMA RICOGNI', 'Sparatutto'),
    _ph('it_h014', 'DRAGO ETA', 'GDR'),
    _ph('it_h015', 'SUPER SCONTRO', 'Combattimento'),
    _ph('it_h016', 'ANIMALE INCROCIO', 'Simulazione'),
    _ph('it_h017', 'STRADA LOTTATORE', 'Combattimento'),
    _ph('it_h018', 'INGRANAGGI GUERRA', 'Sparatutto'),
    _ph('it_h019', 'RAZZO CAMPIONATO', 'Sport'),
    _ph('it_h020', 'PRINCIPE PERSIA', 'Azione'),
    _ph('it_h021', 'CANI GUARDIA', 'Mondo Aperto'),
    _ph('it_h022', 'LUCE MORENTE', 'Orrore'),
    _ph('it_h023', 'UOMO RAGNO', 'Azione'),
    _ph('it_h024', 'GUERRE STELLARI', 'Azione'),
    _ph('it_h025', 'CHIAMATA DOVERE', 'Sparatutto'),
    _ph('it_h026', 'LEGA LEGGENDE', 'MOBA'),
    _ph('it_h027', 'BALDURS CANCELLO', 'GDR'),
    _ph('it_h028', 'GRIDO LONTANO', 'Sparatutto'),
    _ph('it_h029', 'BISOGNO VELOCITA', 'Corsa'),
    _ph('it_h030', 'CITTA ORIZZONTI', 'Simulazione'),
    _ph('it_h031', 'DIAVOLO PIANGE', 'Azione'),
    _ph('it_h032', 'OMBRA COLOSSO', 'Avventura'),
    _ph('it_h033', 'GUERRA TOTALE', 'Strategia'),
    _ph('it_h034', 'MARE DEI LADRI', 'Avventura'),
    _ph('it_h035', 'VERTICE LEGGENDE', 'Battle Royale'),
    _ph('it_h036', 'ETA DEGLI IMPERI', 'Strategia'),
    _ph('it_h037', 'FERRO RACCOLTO', 'Strategia'),
    _ph('it_h038', 'GIUSTA CAUSA', 'Azione'),
    _ph('it_h039', 'ARCA PERDUTA', 'MMORPG'),
    _ph('it_h040', 'CUORI SELVAGGI', 'Azione'),
    _ph('it_h041', 'GIORNI ANDATI', 'Azione'),
    _ph('it_h042', 'SINISTRA MORTE', 'Sparatutto'),
    _ph('it_h043', 'ISOLA DEI MORTI', 'Sopravvivenza'),
    _ph('it_h044', 'RAGAZZI CADUTA', 'Party'),
    _ph('it_h045', 'ROCCIA PROFONDA', 'Coop'),
    _ph('it_h046', 'MALE DENTRO', 'Orrore'),
    _ph('it_h047', 'LEGO STELLE', 'Avventura'),
    _ph('it_h048', 'OMBRA MORDOR', 'Azione'),
    _ph('it_h049', 'DESTINO ETERNO', 'Sparatutto'),
    _ph('it_h050', 'TERRE ESTERNE', 'Avventura'),
  ];

  static PuzzleModel _p(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.easy, language: 'it',
      );

  static PuzzleModel _pm(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.medium, language: 'it',
      );

  static PuzzleModel _ph(String id, String word, String cat) => PuzzleModel(
        id: id, word: word, category: cat,
        difficulty: Difficulty.hard, language: 'it',
      );
}
